version: "3.1"

services:
  fileserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../../dev.env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      # DEV_NGINX_PORT: ${DEV_NGINX_PORT}
      # DEV_SERVER_PORT: ${DEV_SERVER_PORT}
      # DEV_FRONTEND_SERVER_PORT: ${DEV_FRONTEND_SERVER_PORT}
      # IMAGES_BASEPATH: ${IMAGES_BASEPATH}
    network_mode: "host"
    volumes:
      - /mnt/oogergo:/mnt/oogergo