paths = {
    "Project": {"Patient", "Contact"},
    "Patient": {"Project", "Study", "FormAnnotation", "Annotation"},
    "Study": {"Patient", "Series", "FormAnnotation", "Annotation", "StudyTag"},
    "Series": {"Study", "ImageInstance", "FormAnnotation", "Annotation"},
    "ImageInstance": {
        "Series",
        "Segmentation",
        "ModelSegmentation",
        "FormAnnotation",
        "DeviceInstance",
        "Scan",
        "Modality",
        "SourceInfo",
        "ImageInstanceTag",
        "SubTaskImageLink",
    },
    "DeviceInstance": {"DeviceModel"},
    "DeviceModel": {"DeviceInstance"},
    "Segmentation": {
        "ImageInstance",
        "Feature",
        "Creator",
        "SubTask",
        "SegmentationTag",
    },
    "ModelSegmentation": {
        "ImageInstance",
        "Model",
    },
    "Model": {
        "Feature",
    },
    "FormAnnotation": {
        "ImageInstance",
        "Study",
        "Patient",
        "FormSchema",
        "Creator",
    },
    "Feature": {
        "CompositeFeature",
    },
    "CompositeFeature": {
        "Feature",
    },
    "Task": {"TaskDefinition", "TaskState", "SubTask"},
    "SubTask": {"Task", "TaskState", "Creator", "SubTaskImageLink"},
    "SubTaskImageLink": {"SubTask", "ImageInstance"},
}
