paths = {
    "Project": {"Patient", "Contact"},
    "Patient": {"Project", "Study", "FormAnnotation", "Annotation"},
    "Study": {"Patient", "Series", "FormAnnotation", "Annotation", "StudyTag"},
    "Series": {"Study", "ImageInstance", "FormAnnotation", "Annotation"},
    "ImageInstance": {
        "Series",
        "Annotation",
        "FormAnnotation",
        "DeviceInstance",
        "Scan",
        "Modality",
        "SourceInfo",
        "ImageInstanceTag",
        "SubTaskImageLink",
    },
    "DeviceInstance": {"DeviceModel"},
    "DeviceModel": {"DeviceInstance"},
    "Annotation": {
        "ImageInstance",
        "Patient",
        "Study",
        "Series",
        "AnnotationData",
        "AnnotationType",
        "Feature",
        "Creator",
        "AnnotationTag",
    },
    "AnnotationData": {"Annotation"},
    "FormAnnotation": {
        "ImageInstance",
        "Study",
        "Patient",
        "FormSchema",
        "Creator",
    },
    "Task": {"TaskDefinition", "TaskState", "SubTask"},
    "SubTask": {"Task", "TaskState", "Creator", "SubTaskImageLink"},
    "SubTaskImageLink": {"SubTask", "ImageInstance"},
}