FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libxcb1 libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


COPY orm /app/orm
RUN pip install -e /app/orm

COPY server /app/server
RUN pip install --no-cache-dir -r /app/server/requirements.txt

EXPOSE 8000

WORKDIR /app

CMD ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/server", "--reload-dir", "/app/orm"]