name: eyened-platform-dev

services:
  
  fileserver:
    env_file: .env
    image: nginx:latest    
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - <thumbnails_path>:/storage/thumbnails:ro
      - <filestorage_mount>:<filestorage_mount>:ro

  database:
    env_file: .env
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${EYENED_DATABASE_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 5s
      retries: 10
 
  adminer:
    env_file: .env
    image: adminer:latest
    restart: always
    ports:
      - "${DEV_ADMINER_PORT}:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=database

volumes:
  db_data:
