# https://hub.docker.com/_/mysql
version: '3.1'

services:
  test-database:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_DB_ROOT_PASSWORD}
    env_file: 
      - .env
    ports:
      - "${MYSQL_TEST_DB_PORT}:3306"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: test-database
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_TEST_DB_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80

  test-alembic:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile-alembic
    environment:
      ALEMBIC_AUTO_MIGRATION: ${ALEMBIC_AUTO_MIGRATION}
    env_file: 
      - .env
    volumes:
      - ./migration_output:/app/migration_output 
    depends_on:
      - test-database