version: '3.1'

services:
  test-alembic:
    build:
      context: ..
      dockerfile: ./migrations/Dockerfile
    volumes:
      - ./migration_output:/app/migration_output 
    depends_on:
      test-database:
        condition: service_healthy