# This is the docker-compose file for the database and phpmyadmin
version: '3.1'

services:
  test-database:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${TEST_DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 5s
      retries: 10
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: test-database
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_VERBOSE: "false"      
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      test-database:
        condition: service_healthy
