version: "3.1"

name: eyened-platform

services:

  database:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ${DATABASE_PATH}:/var/lib/mysql 
    ports:
      - "${DATABASE_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DATABASE_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 5s
      retries: 10

  api-server:
    user: "${USERID:-1000}:${GROUPID:-1000}"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2s
      timeout: 5s
      retries: 10
    depends_on:
      database:
        condition: service_healthy
    environment:
      - IMAGES_BASEPATH=/images
      - SEGMENTATIONS_ZARR_STORE=/storage/segmentations.zarr
      - THUMBNAILS_PATH=/storage/thumbnails
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=database
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=3306
      - DATABASE_NAME=eyened_database
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ${IMAGES_BASEPATH}:/images
      - ${SEGMENTATIONS_ZARR_STORE}:/storage/segmentations.zarr
      - ${THUMBNAILS_PATH}:/storage/thumbnails

  redis:
    user: "${USERID:-1000}:${GROUPID:-1000}"
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10

  worker:
    user: "${USERID:-1000}:${GROUPID:-1000}"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_HOST=database
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=3306
      - DATABASE_NAME=eyened_database
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - IMAGES_BASEPATH=/images
      - SEGMENTATIONS_ZARR_STORE=/storage/segmentations.zarr
      - THUMBNAILS_PATH=/storage/thumbnails
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    volumes:
      - ${IMAGES_BASEPATH}:/images
      - ${SEGMENTATIONS_ZARR_STORE}:/storage/segmentations.zarr
      - ${THUMBNAILS_PATH}:/storage/thumbnails
    restart: always

  fileserver:
    build:
      context: .
      dockerfile: Dockerfile.fileserver
    depends_on:
      api-server:
        condition: service_healthy
    volumes:
      - ${IMAGES_BASEPATH}:/images
      - ${THUMBNAILS_PATH}:/thumbnails
    ports:
      - ${PORT}:80

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "18080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=database

