"""task creator and state

Revision ID: 62b55e9c9e70
Revises: 31212c7f33fd
Create Date: 2025-09-22 11:43:18.044096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62b55e9c9e70'
down_revision: Union[str, None] = '31212c7f33fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('TaskStateName', table_name='TaskState')
    op.drop_table('TaskState')
    # op.drop_index('fk_FormAnnotation_FormAnnotation1', table_name='FormAnnotation')
    op.add_column('Task', sa.Column('CreatorID', sa.Integer(), nullable=True))
    op.add_column('Task', sa.Column('TaskState', sa.Enum('NotStarted', 'Busy', 'Finished', 'Aborted', 'Archived', name='taskstate'), nullable=False))
    op.create_foreign_key(None, 'Task', 'Creator', ['CreatorID'], ['CreatorID'])
    # ### end Alembic commands ###


