"""Bar'ts migration

Revision ID: 45eed982b514
Revises: 832ed384515f
Create Date: 2025-07-01 15:21:46.565505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45eed982b514'
down_revision: Union[str, None] = '832ed384515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnnotationTypeFeature',
    sa.Column('AnnotationTypeID', sa.Integer(), nullable=False),
    sa.Column('FeatureID', sa.Integer(), nullable=False),
    sa.Column('FeatureIndex', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AnnotationTypeID'], ['AnnotationType.AnnotationTypeID'], ),
    sa.ForeignKeyConstraint(['FeatureID'], ['Feature.FeatureID'], ),
    sa.PrimaryKeyConstraint('AnnotationTypeID', 'FeatureID', 'FeatureIndex')
    )
    op.create_index('fk_AnnotationTypeFeature_AnnotationType1_idx', 'AnnotationTypeFeature', ['AnnotationTypeID'], unique=False)
    op.create_index('fk_AnnotationTypeFeature_Feature1_idx', 'AnnotationTypeFeature', ['FeatureID'], unique=False)
    op.create_foreign_key(None, 'Annotation', 'Annotation', ['AnnotationReferenceID'], ['AnnotationID'])
    op.add_column('AnnotationData', sa.Column('AnnotationPlane', sa.Enum('PRIMARY', 'SECONDARY', 'TERTIARY', 'VOLUME', name='annotationplane'), nullable=False))
    op.alter_column('AnnotationData', 'DatasetIdentifier',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.drop_column('AnnotationData', 'MediaType')
    op.add_column('AnnotationType', sa.Column('DataRepresentation', sa.Enum('BINARY', 'RG_MASK', 'FLOAT', 'MULTI_LABEL', 'MULTI_CLASS', name='datarepresentation'), nullable=False))
    op.drop_index('AnnotationTypeNameInterpretation_UNIQUE', table_name='AnnotationType')
    op.drop_column('AnnotationType', 'Interpretation')
    op.add_column('Contact', sa.Column('Orcid', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('Creator', sa.Column('EmployeeIdentifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('Creator', sa.Column('PasswordHash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('Creator', 'MSN')
    op.drop_column('Feature', 'Modality')
    op.drop_constraint('fk_FormAnnotation_ImageInstance1', 'FormAnnotation', type_='foreignkey')
    op.create_foreign_key(None, 'FormAnnotation', 'ImageInstance', ['ImageInstanceID'], ['ImageInstanceID'])
    op.alter_column('FormSchema', 'SchemaName',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('ImageInstance', 'DeviceInstanceID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('ImageInstance', 'ThumbnailIdentifier')
    op.alter_column('Patient', 'PatientIdentifier',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.add_column('Project', sa.Column('DOI', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.drop_constraint('fk_Series_Study1', 'Series', type_='foreignkey')
    op.create_foreign_key(None, 'Series', 'Study', ['StudyID'], ['StudyID'])
    op.create_index('StudyDate_idx', 'Study', ['StudyDate'], unique=False)
    op.add_column('SubTask', sa.Column('Comments', sa.Text(), nullable=True))
    op.drop_column('SubTaskImageLink', 'SubTaskImageLinkID')
    op.create_unique_constraint(None, 'TaskState', ['TaskStateName'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TaskState', type_='unique')
    op.add_column('SubTaskImageLink', sa.Column('SubTaskImageLinkID', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('SubTask', 'Comments')
    op.drop_index('StudyDate_idx', table_name='Study')
    op.drop_constraint(None, 'Series', type_='foreignkey')
    op.create_foreign_key('fk_Series_Study1', 'Series', 'Study', ['StudyID'], ['StudyID'], ondelete='CASCADE')
    op.drop_column('Project', 'DOI')
    op.alter_column('Patient', 'PatientIdentifier',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.add_column('ImageInstance', sa.Column('ThumbnailIdentifier', mysql.VARCHAR(length=256), nullable=True))
    op.alter_column('ImageInstance', 'DeviceInstanceID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('FormSchema', 'SchemaName',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.drop_constraint(None, 'FormAnnotation', type_='foreignkey')
    op.create_foreign_key('fk_FormAnnotation_ImageInstance1', 'FormAnnotation', 'ImageInstance', ['ImageInstanceID'], ['ImageInstanceID'], ondelete='CASCADE')
    op.add_column('Feature', sa.Column('Modality', mysql.ENUM('OCT', 'CF'), nullable=True))
    op.add_column('Creator', sa.Column('MSN', mysql.CHAR(length=6), nullable=True))
    op.drop_column('Creator', 'PasswordHash')
    op.drop_column('Creator', 'EmployeeIdentifier')
    op.drop_column('Contact', 'Orcid')
    op.add_column('AnnotationType', sa.Column('Interpretation', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=45), nullable=False))
    op.create_index('AnnotationTypeNameInterpretation_UNIQUE', 'AnnotationType', ['AnnotationTypeName', 'Interpretation'], unique=True)
    op.drop_column('AnnotationType', 'DataRepresentation')
    op.add_column('AnnotationData', sa.Column('MediaType', mysql.VARCHAR(length=45), nullable=False))
    op.alter_column('AnnotationData', 'DatasetIdentifier',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('AnnotationData', 'AnnotationPlane')
    op.drop_constraint(None, 'Annotation', type_='foreignkey')
    op.drop_index('fk_AnnotationTypeFeature_Feature1_idx', table_name='AnnotationTypeFeature')
    op.drop_index('fk_AnnotationTypeFeature_AnnotationType1_idx', table_name='AnnotationTypeFeature')
    op.drop_table('AnnotationTypeFeature')
    # ### end Alembic commands ###
