"""test

Revision ID: 443293066fa3
Revises: 832ed384515f
Create Date: 2025-05-21 10:38:01.121227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '443293066fa3'
down_revision: Union[str, None] = '832ed384515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_Annotation_Annotation1'), 'Annotation', 'Annotation', ['AnnotationReferenceID'], ['AnnotationID'])
    op.alter_column('ImageInstance', 'FileChecksum',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=True)
    op.alter_column('ImageInstance', 'DataHash',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=True)
    op.create_index('StudyDate_idx', 'Study', ['StudyDate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('StudyDate_idx', table_name='Study')
    op.alter_column('ImageInstance', 'DataHash',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.alter_column('ImageInstance', 'FileChecksum',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_Annotation_Annotation1'), 'Annotation', type_='foreignkey')
    # ### end Alembic commands ###
