"""test

Revision ID: f198802eada6
Revises: 62b55e9c9e70
Create Date: 2025-10-08 12:15:05.803660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f198802eada6'
down_revision: Union[str, None] = '62b55e9c9e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_FormAnnotation_FormAnnotationReferenceID', table_name='FormAnnotation')
    op.add_column('ImageInstance', sa.Column('RetinalImageQuality', sa.Integer(), nullable=True))
    op.add_column('ImageInstance', sa.Column('ChoroidalImageQuality', sa.Integer(), nullable=True))
    op.add_column('ImageInstance', sa.Column('AltDatasetIdentifier', sa.String(length=256), nullable=True))
    op.alter_column('ImageInstance', 'DeviceInstanceID',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=True)
    op.alter_column('ImageInstance', 'DeviceInstanceID',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('ImageInstance', 'AltDatasetIdentifier')
    op.drop_column('ImageInstance', 'ChoroidalImageQuality')
    op.drop_column('ImageInstance', 'RetinalImageQuality')
    op.create_index('ix_FormAnnotation_FormAnnotationReferenceID', 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    # ### end Alembic commands ###
