"""imageinstance_columns_and_studyuid_to_series

Revision ID: 5ffd55a02beb
Revises: 62b55e9c9e70
Create Date: 2025-10-22 10:49:48.471731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ffd55a02beb'
down_revision: Union[str, None] = '62b55e9c9e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # -- This is an issue from the last migration #TODO: check if this is still needed
    # op.drop_index('ix_FormAnnotation_FormAnnotationReferenceID', table_name='FormAnnotation')

    op.add_column('ImageInstance', sa.Column('AltDatasetIdentifier', sa.String(length=256), nullable=True))
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=False)
    op.add_column('Series', sa.Column('StudyInstanceUid', sa.String(length=64), nullable=True))
    op.create_index('StudyInstanceUidSeriesInstanceUid_UNIQUE', 'Series', ['StudyInstanceUid', 'SeriesInstanceUid'], unique=True)
    op.drop_index('StudyInstanceUid_UNIQUE', table_name='Study')
    op.drop_column('Study', 'StudyInstanceUid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Study', sa.Column('StudyInstanceUid', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('StudyInstanceUid_UNIQUE', 'Study', ['StudyInstanceUid'], unique=True)
    op.drop_index('StudyInstanceUidSeriesInstanceUid_UNIQUE', table_name='Series')
    op.drop_column('Series', 'StudyInstanceUid')
    op.alter_column('ImageInstance', 'Laterality',
               existing_type=mysql.ENUM('L', 'R'),
               nullable=True)
    op.drop_column('ImageInstance', 'AltDatasetIdentifier')
    op.create_index('ix_FormAnnotation_FormAnnotationReferenceID', 'FormAnnotation', ['FormAnnotationReferenceID'], unique=False)
    # ### end Alembic commands ###
