"""add TaskProject

Revision ID: 99724789b34d
Revises: 4eae42457fa2
Create Date: 2026-08-20

Creates the declaration table: the projects a task may contain, stated
directly rather than derived by walking every image up to its patient's
project. Later tasks add the foreign keys that hold data inside this
declaration; this migration only creates the table and seeds it from what
each task currently derives.

Not autogenerated. This worktree has no dev/.env or dev/.env.alembic, and the
DDL grant this migration needs only works from inside the compose network --
not from the host, not via `docker exec` -- so `alembic revision
--autogenerate` could not be run here. Hand-authored to match the shape
autogenerate would produce; a human should diff this against a live schema
before it is trusted unreviewed.

No strict-SQL-mode guard, unlike its two predecessors. That guard exists to
catch a NOT NULL conversion silently rewriting a missed row to 0 -- relevant
when a column is added nullable, backfilled by UPDATE, and only then
tightened with `MODIFY ... NOT NULL`. TaskID and ProjectID here are never
nullable: they are the table's primary key, declared NOT NULL at CREATE TABLE
time, and the backfill below is an INSERT of brand-new rows, not an UPDATE of
existing ones. There is no tightening step for the guard to protect.

No chunking, unlike its two predecessors. Those backfills rewrite 1.85M and
several hundred thousand rows respectively and are chunked specifically to
avoid holding row locks on a live, populated table for tens of seconds. This
one inserts on the order of 108 rows, computed by a single indexed join and
written to a table that has no rows and no readers yet (it does not exist
until this same migration creates it) -- chunking machinery here would be
noise with nothing to protect against.

Both DDL statements below (CREATE TABLE, CREATE INDEX) run and implicitly
commit before the INSERT is ever sent, so a re-run can reach this INSERT with
the table already created, indexed, and populated -- not only from a crash
before the INSERT's own transaction committed, but from an operator recovery
move (`alembic stamp <down_revision>` followed by `alembic upgrade head`) or
a backup restored after the DDL committed. The INSERT is written as an
anti-join against TaskProject itself (`LEFT JOIN ... WHERE tp.TaskID IS
NULL`), so a row already present is simply not selected again; re-running it
against a populated table inserts only what is still missing and is a no-op
once the declaration is complete. `INSERT IGNORE` is deliberately not used
instead: it would downgrade a foreign-key violation or truncation to a
warning, silently dropping a row instead of failing loud -- exactly the
failure a later task's equivalence gate depends on surfacing.

The INSERT reads at READ COMMITTED from inside an autocommit block. Neither
half of that pairing works without the other; the comment above the statement
says what each one is holding up and what breaks when it is dropped.
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa
from sqlalchemy.engine import Connection


# revision identifiers, used by Alembic.
revision: str = '99724789b34d'
down_revision: Union[str, None] = '4eae42457fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(conn: Connection, table: str) -> bool:
    """Make CREATE TABLE re-runnable. MySQL has no CREATE TABLE IF NOT EXISTS via op.create_table."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t"
            ),
            {"t": table},
        ).scalar()
    )


def _index_exists(conn: Connection, table: str, index: str) -> bool:
    """Make CREATE INDEX re-runnable. MySQL has no CREATE INDEX IF NOT EXISTS."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.STATISTICS "
                "WHERE TABLE_SCHEMA = DATABASE() "
                "AND TABLE_NAME = :t AND INDEX_NAME = :i"
            ),
            {"t": table, "i": index},
        ).scalar()
    )


def upgrade() -> None:
    conn = op.get_bind()
    # DDL commits implicitly in MySQL, so a half-applied run (table created,
    # index not yet created, or vice versa) must be resumable without erroring
    # on "table already exists" / duplicate index. Guarded individually, in
    # the order they are created, so a re-run picks up wherever it stopped.
    if not _table_exists(conn, "TaskProject"):
        op.create_table(
            "TaskProject",
            sa.Column("TaskID", sa.Integer(), nullable=False),
            sa.Column("ProjectID", sa.Integer(), nullable=False),
            sa.Column(
                "DateInserted",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            ),
            # Named, and the name of the first one is load-bearing.
            #
            # Deleting a task emits ONE `DELETE FROM Task` and lets InnoDB
            # cascade into two independent branches: SubTask -> its image
            # links, and TaskProject. A later migration adds
            # `fk_SubTaskImageLink_TaskProject`, a RESTRICT key from the link
            # rows to this table, so if the TaskProject branch runs FIRST it
            # withdraws a declaration the link rows still reference and the
            # delete dies with ERROR 1451 -- on every task that has both
            # images and a declaration, which is every real task.
            #
            # InnoDB walks a parent's referencing constraints in constraint-id
            # order (`schema/name`), compared BYTE-WISE and case-sensitively --
            # measured, not assumed. So the SubTask branch has to sort first.
            # We do not control SubTask's constraint name: 2025_09_15's
            # `create_foreign_key(None, ...)` leaves MySQL to pick it, and it
            # has already come out as both `SubTask_ibfk_1` (live) and
            # `SubTask_ibfk_2` (built from orm_baseline). `fk_TaskProject_Task`
            # loses to every name that key has plausibly worn:
            #
            #   vs SubTask_ibfk_1 / _2   'S' 0x53 < 'f' 0x66      SubTask first
            #   vs fk_SubTask_Task1      shared "fk_" prefix,
            #                            then 'S' 0x53 < 'T' 0x54  SubTask first
            #
            # (`fk_SubTask_Task1` is the legacy name, still worn by the INDEX;
            # under it an UNNAMED key here -- `TaskProject_ibfk_1` -- would put
            # TaskProject first and fail 1451.) Renaming this constraint is a
            # correctness change, not a cosmetic one. The containment migration
            # asserts the ordering before its first DDL so a rename fails there
            # rather than at delete time.
            sa.ForeignKeyConstraint(
                ["TaskID"],
                ["Task.TaskID"],
                name="fk_TaskProject_Task",
                ondelete="CASCADE",
            ),
            # Named only for symmetry and so `--autogenerate` sees the same
            # name the model declares. It references Project, not Task, so it
            # is not on the ordering path above.
            sa.ForeignKeyConstraint(
                ["ProjectID"],
                ["Project.ProjectID"],
                name="fk_TaskProject_Project",
                ondelete="RESTRICT",
            ),
            sa.PrimaryKeyConstraint("TaskID", "ProjectID"),
        )
    # Named explicitly: InnoDB requires an index on the referencing side of
    # the ProjectID foreign key and creates one itself, called `ProjectID`, if
    # this one is missing. That index is undeclarable in the ORM model and
    # undroppable in the database (ERROR 1553: "needed in a foreign key
    # constraint"), so confirm it exists under the name the model gives it.
    #
    # Raw SQL, not op.create_index: on a brand-new empty table the online-DDL
    # clause is moot, but a re-run that finds the table already created and
    # populated with only the index missing -- a crash between the two DDL
    # statements -- would otherwise run CREATE INDEX against live rows with no
    # assertion that it stays online, the same rule the sibling migration's
    # ALTER TABLE statements follow.
    if not _index_exists(conn, "TaskProject", "ix_TaskProject_Project"):
        # No commas before the clauses: those are ALTER TABLE syntax, where the
        # statement is a comma-separated list of alter specifications. CREATE
        # INDEX takes them space-separated, and the comma form is ERROR 1064 on
        # 8.0.27 -- which would strand this migration with the table created
        # and the index missing, since CREATE TABLE has already committed.
        op.execute(
            "CREATE INDEX ix_TaskProject_Project ON TaskProject (ProjectID) "
            "ALGORITHM=INPLACE LOCK=NONE"
        )

    # The declaration seeded from what each task currently derives: the set
    # of projects reached by walking every image a task's subtasks reference,
    # up through Series and Study, to the patient's project. This is the one
    # moment the derived and declared answers must agree; a later task
    # asserts that before any constraint goes on top of this table.
    #
    # Deliberately does not filter ImageInstance.Inactive: a soft-deleted
    # image still ties its project to the task, and excluding it would narrow
    # the declaration below what the (still-present) links require -- the
    # same reasoning as the walk this replaces.
    #
    # The trailing LEFT JOIN / WHERE ... IS NULL is an anti-join against
    # TaskProject itself, not part of the derivation above: it is what makes
    # a re-run against an already-populated table insert only the rows still
    # missing instead of dying on a duplicate-key error.
    # The INSERT ... SELECT below reads six tables it does not write. At
    # REPEATABLE READ, MySQL takes a shared next-key lock on every source row
    # it reads on the way to the rows it inserts -- 57k of them against
    # production-sized data, with concurrent inserts into SubTaskImageLink and
    # of new SubTasks stalling behind them for as long as the statement runs.
    # What this seeds is a derivation, and a snapshot-consistent read of the
    # sources buys it nothing worth blocking live writers for: READ COMMITTED
    # reads the same rows and takes no locks on them at all.
    #
    # Reaching READ COMMITTED is the awkward part, and both halves of what
    # follows are load-bearing.
    #
    # `SET SESSION transaction_isolation` only affects transactions that begin
    # after it. Issued while one is already open, MySQL accepts it silently and
    # the running transaction keeps the isolation it started with -- so it has
    # to be issued with no transaction in progress. On a first run the DDL
    # above has just implicitly committed and there is none; on a re-run the
    # DDL is skipped, only the two information_schema probes have run, and they
    # have left one open. A bare SET is therefore a fix that verifies green
    # against a fresh database and silently takes the full lock footprint on
    # the recovery path this migration was written to support.
    #
    # `autocommit_block()` is what guarantees no transaction is in progress: it
    # commits alembic's transaction through alembic's own transaction object
    # and switches the connection to AUTOCOMMIT, so the SET lands between
    # transactions on both paths and the INSERT commits on its own. Committing
    # the connection directly (`conn.commit()`) closes the transaction too, but
    # it deactivates the object alembic is holding: everything after it
    # autobegins a transaction alembic never commits, and the UPDATE of
    # alembic_version is lost at connection close -- table created and seeded,
    # revision never stamped.
    #
    # The block on its own is not enough either. AUTOCOMMIT changes transaction
    # boundaries, not isolation: without the SET, the statement inside the
    # block still runs at REPEATABLE READ and still takes every source lock.
    #
    # The isolation is then put back explicitly. Migrations later in the same
    # `alembic upgrade` run share this connection -- on MySQL alembic gives
    # each migration its own transaction, but not its own session -- and one
    # left at READ COMMITTED would quietly change how they read. Leaving the
    # block restores it as well, but only as a side effect of undoing
    # AUTOCOMMIT; that is alembic's bookkeeping, not a promise about isolation,
    # so the restore is stated here rather than inherited from it.
    #
    # This needs row-based binary logging, which is what this deployment runs.
    # InnoDB cannot statement-log at READ COMMITTED, so under
    # binlog_format=STATEMENT the INSERT fails with ERROR 1665 rather than
    # logging something wrong.
    with context.get_context().autocommit_block():
        # The block swaps in a connection at AUTOCOMMIT isolation, so the bind
        # has to be re-fetched here rather than reused from above.
        block_conn = op.get_bind()
        prior_isolation = block_conn.execute(
            sa.text("SELECT @@SESSION.transaction_isolation")
        ).scalar()
        block_conn.execute(
            sa.text("SET SESSION transaction_isolation = 'READ-COMMITTED'")
        )
        try:
            op.execute("""
                INSERT INTO TaskProject (TaskID, ProjectID)
                SELECT DISTINCT st.TaskID, p.ProjectID
                FROM SubTask st
                  JOIN SubTaskImageLink sil ON sil.SubTaskID = st.SubTaskID
                  JOIN ImageInstance ii ON ii.ImageInstanceID = sil.ImageInstanceID
                  JOIN Series se ON se.SeriesID = ii.SeriesID
                  JOIN Study sy ON sy.StudyID = se.StudyID
                  JOIN Patient p ON p.PatientID = sy.PatientID
                  LEFT JOIN TaskProject tp
                    ON tp.TaskID = st.TaskID AND tp.ProjectID = p.ProjectID
                WHERE tp.TaskID IS NULL
            """)
        finally:
            # Read back rather than named literally, so this restores what the
            # session was actually on and not what the server default is
            # assumed to be.
            block_conn.execute(
                sa.text("SET SESSION transaction_isolation = :level"),
                {"level": prior_isolation},
            )


def downgrade() -> None:
    # DROP TABLE removes its indexes with it, so there is nothing for a
    # separate DROP INDEX to do here; guarding the table drop alone is
    # sufficient to make this re-runnable.
    conn = op.get_bind()
    if _table_exists(conn, "TaskProject"):
        op.drop_table("TaskProject")
