"""SubTaskImageLink containment

Revision ID: 2db0e63195db
Revises: b45090e1544e
Create Date: 2026-08-20

Gives SubTaskImageLink its own TaskID and ProjectID and points three foreign
keys at them. Two of the three replace the single-column keys the table already
had, carrying the denormalized copy alongside; the third,
`fk_SubTaskImageLink_TaskProject`, is new and is the point of the whole design:
from the moment it lands, an image from a project its task has not declared
cannot be linked by any writer -- service, script, or raw SQL -- because the
database refuses the row.

The columns and the keys ship in one migration because they have to. TaskID is
NOT NULL and no application listener can fill it for `create_from_imagesets`:
at before_flush the Task row does not exist, so the pending SubTask.TaskID is
still None. What fills it is SQLAlchemy's unit of work syncing the composite key
(SubTaskID, TaskID) -> SubTask during the flush, after the parent's INSERT.
Split the columns from the key and the script write path is broken in between.

Expect seconds. Spec 10.6 measures the three foreign keys at 1.7 s over the
87,454 rows this table holds; that figure is already the COPY-rebuild cost. A
run that takes a minute is a signal that something is wrong, not the plan being
met -- ImageInstance and Series are the tables that carry a write window, and
they were converted a migration ago.

The gate at the top of `upgrade` is the reason this file is not just DDL. This
is the one moment declared and derived coexist: once the read path switches to
the declaration there is nothing left to compare against. See `upgrade` for why
its two directions are deliberately not symmetric.

Not autogenerated. This worktree has no dev/.env or dev/.env.alembic, and the
DDL grant this migration needs only works from inside the compose network, so
`alembic revision --autogenerate` could not be run here. Hand-authored to match
the shape autogenerate would produce -- every index and constraint name is
copied from the model's __table_args__ verbatim, because a name derived from
the columns instead would differ by a word and the next autogenerate would emit
a spurious drop-and-add for it forever -- then parsed and executed end to end
against a throwaway MySQL 8.0.27 on a stub of the pre-migration schema. A human
should still diff it against the live schema before it is trusted unreviewed.

Re-runnable, like its predecessors and for the same reason: MySQL commits DDL
implicitly, so the statements below commit one at a time and an interrupted run
-- a crash, a timeout on the rebuild, or an operator recovery (`alembic stamp
<down_revision>` then `alembic upgrade head`) -- can re-enter this function with
any prefix already applied. Each step is guarded by the state it would produce.
Nothing that can raise runs after the first ALTER: the gate and the
single-column-FK discovery, the only two things here that can fail on a
well-formed database, both happen before any DDL. Verified by killing the run at
every statement boundary and re-running from each, upgrade and downgrade alike,
with a negative control on an unguarded copy.
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa
from sqlalchemy.engine import Connection


# revision identifiers, used by Alembic.
revision: str = '2db0e63195db'
down_revision: Union[str, None] = 'b45090e1544e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The (task, project) pairs the image links imply, derived the long way round.
#
# Walks to Patient rather than reading SubTaskImageLink.TaskID/.ProjectID
# because the gate runs BEFORE this migration's ADD COLUMN: a gate written
# against those columns fails with "Unknown column", which reads like a broken
# migration rather than a failing check. It is also the honest comparison --
# reading the columns this migration is about to populate would compare the
# backfill against itself.
_DERIVED = """
    SELECT DISTINCT st.TaskID AS TaskID, p.ProjectID AS ProjectID
    FROM SubTask st
      JOIN SubTaskImageLink sil ON sil.SubTaskID = st.SubTaskID
      JOIN ImageInstance ii ON ii.ImageInstanceID = sil.ImageInstanceID
      JOIN Series se ON se.SeriesID = ii.SeriesID
      JOIN Study sy ON sy.StudyID = se.StudyID
      JOIN Patient p ON p.PatientID = sy.PatientID
"""

# (name, columns) for the three indexes this migration adds to
# SubTaskImageLink, in the order the model declares them.
#
# (ImageInstanceID, ProjectID) and (SubTaskID, TaskID) lead their indexes
# because each backs a foreign key. SubTaskID moves to third position in the
# first one, so it is no longer a two-column lookup for (image, subtask) the
# way ix_SubTaskImageLink_Image_SubTask was: an equality on ImageInstanceID
# leaves a handful of rows, so the residual scan is not measurable, but this
# covers the same *queries* by a slightly worse route rather than covering the
# same lookups.
_NEW_INDEXES = (
    ("ix_SubTaskImageLink_Image_Project", "ImageInstanceID, ProjectID, SubTaskID"),
    ("ix_SubTaskImageLink_SubTask_Task", "SubTaskID, TaskID"),
    ("ix_SubTaskImageLink_Task_Project", "TaskID, ProjectID"),
)

# The indexes the three above replace. Dropped last, after the new foreign keys
# exist and the old ones are gone: dropping an index a live foreign key is
# bound to is refused with ERROR 1553, and dropping it before the replacement
# is in place leaves a window with no index to enforce against.
_OLD_INDEXES = (
    "ix_SubTaskImageLink_Image_SubTask",
    "fk_SubTaskImageLink_SubTask1_idx",
    "fk_SubTaskImageLink_ImageInstance1_idx",
)

# (name, columns, referenced table, referenced columns, extra clauses).
_NEW_FKS = (
    ("fk_SubTaskImageLink_SubTask_Task", "SubTaskID, TaskID",
     "SubTask", "SubTaskID, TaskID", "ON UPDATE CASCADE ON DELETE CASCADE"),
    ("fk_SubTaskImageLink_Image_Project", "ImageInstanceID, ProjectID",
     "ImageInstance", "ImageInstanceID, ProjectID",
     "ON UPDATE CASCADE ON DELETE CASCADE"),
    # No ON UPDATE and no ON DELETE, both deliberately. Cascading an update
    # would let a change to TaskProject silently rewrite link rows; cascading a
    # delete would let a declaration be withdrawn out from under the links that
    # depend on it. The point of this key is that it refuses instead.
    ("fk_SubTaskImageLink_TaskProject", "TaskID, ProjectID",
     "TaskProject", "TaskID, ProjectID", ""),
)


# Deliberately copied from the sibling migrations rather than imported: a
# migration that imports from another one breaks the moment that other file is
# squashed away.
def _column_exists(conn: Connection, table: str, column: str) -> bool:
    """Make ADD COLUMN re-runnable. MySQL has no ADD COLUMN IF NOT EXISTS."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.COLUMNS "
                "WHERE TABLE_SCHEMA = DATABASE() "
                "AND TABLE_NAME = :t AND COLUMN_NAME = :c"
            ),
            {"t": table, "c": column},
        ).scalar()
    )


def _index_exists(conn: Connection, table: str, index: str) -> bool:
    """Make ADD INDEX re-runnable. MySQL has no ADD INDEX IF NOT EXISTS."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.STATISTICS "
                "WHERE TABLE_SCHEMA = DATABASE() "
                "AND TABLE_NAME = :t AND INDEX_NAME = :i"
            ),
            {"t": table, "i": index},
        ).scalar()
    )


def _fk_exists(conn: Connection, table: str, name: str) -> bool:
    """Make ADD CONSTRAINT / DROP FOREIGN KEY re-runnable, by constraint name."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.TABLE_CONSTRAINTS "
                "WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = :t "
                "AND CONSTRAINT_NAME = :n AND CONSTRAINT_TYPE = 'FOREIGN KEY'"
            ),
            {"t": table, "n": name},
        ).scalar()
    )


def _single_column_fk(
    conn: Connection, table: str, column: str, referenced: str
) -> Union[str, None]:
    """Name the single-column FK a composite replaces. Reads only.

    The names come from the schema this repository inherited, not from the
    models, so they are discovered rather than hardcoded.

    Restricted to constraints of exactly ONE column, which is load-bearing
    rather than defensive: the composite this migration adds is created BEFORE
    this one is dropped and shares its COLUMN_NAME *and* its
    REFERENCED_TABLE_NAME, so without `c.cols = 1` the query matches both keys
    and the drop could take the new one.

    Returns None when there is nothing to drop -- a re-run that already got
    past the drop, or a table that arrived without the key. Neither is an
    error and they need not be told apart: the answer to both is the same, add
    the composite and drop nothing. Two or more candidates is an error, because
    no rule here could pick between them. Emitting no DDL is what lets
    `upgrade` call this up front and take that error while the schema is whole.
    """
    names = (
        conn.execute(
            sa.text("""
                SELECT k.CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE k
                JOIN (
                    SELECT CONSTRAINT_SCHEMA, CONSTRAINT_NAME, COUNT(*) AS cols
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t
                    GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_NAME
                ) c
                  ON c.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND c.CONSTRAINT_NAME = k.CONSTRAINT_NAME
                WHERE k.TABLE_SCHEMA = DATABASE() AND k.TABLE_NAME = :t
                  AND k.COLUMN_NAME = :c AND k.REFERENCED_TABLE_NAME = :r
                  AND c.cols = 1
            """),
            {"t": table, "c": column, "r": referenced},
        )
        .scalars()
        .all()
    )
    if len(names) > 1:
        raise RuntimeError(
            f"expected at most one single-column FK on {table}.{column} -> "
            f"{referenced}, found {names!r}"
        )
    return names[0] if names else None


def _require_fk_checks_on(conn: Connection) -> None:
    """A COPY rebuild only validates existing rows while this is on.

    With it off, MySQL adds the constraint over data that violates it, the bad
    rows survive, and CHECK TABLE reports OK -- a constraint that lies about
    everything already in the table, with nothing that would ever surface it.
    That would be worse here than anywhere else in this series: the whole point
    of `fk_SubTaskImageLink_TaskProject` is that it is trusted without being
    re-checked. Asserted by `downgrade` too, which restores keys of its own.
    """
    if not conn.execute(sa.text("SELECT @@foreign_key_checks")).scalar():
        raise RuntimeError(
            "foreign_key_checks is off; ADD FOREIGN KEY would create the "
            "constraint without checking a single existing row"
        )


_STRICT_MODES = ("STRICT_ALL_TABLES", "STRICT_TRANS_TABLES")


def _require_strict_sql_mode(conn: Connection) -> None:
    """Refuse to run unless a missed row would fail the tightening, not become 0.

    `MODIFY ... NOT NULL` below is the only check that the backfill left no
    NULLs behind, and it only checks anything under a strict SQL mode: a
    non-strict server silently rewrites a residual NULL to 0, producing link
    rows in project 0 that no scope will ever return -- and then the composite
    foreign key rejects them, mid-rebuild, with nothing to say about which row.
    MySQL also requires a strict mode for the INPLACE path of that statement,
    so without one it is not merely unsafe, it is slower too.
    """
    if conn.dialect.name != "mysql":
        return
    sql_mode = conn.execute(sa.text("SELECT @@SESSION.sql_mode")).scalar() or ""
    if not {mode.strip() for mode in sql_mode.split(",")} & set(_STRICT_MODES):
        raise RuntimeError(
            "this migration requires a strict SQL mode. The session sql_mode is "
            f"{sql_mode!r}, which contains none of {', '.join(_STRICT_MODES)}. "
            "Without one, ALTER TABLE SubTaskImageLink MODIFY TaskID INT NOT NULL "
            "rewrites any row the backfill missed to 0 instead of failing. Set a "
            "strict sql_mode on the server or the connection, then re-run."
        )


def _gate(conn: Connection) -> None:
    """Refuse to proceed if the links imply a declaration nobody made.

    Adding the constraints to data that violates them fails partway through a
    table rebuild, leaving a half-applied migration; failing here costs a
    second.

    The two directions are NOT symmetric and must not be collapsed into one
    number:

    * A pair the links imply but nobody declares is exactly what
      `fk_SubTaskImageLink_TaskProject` will refuse. Abort.
    * A pair declared but unused is legal for the rest of this schema's life --
      a task may declare a project it happens to hold no images from. It cannot
      abort. It does change visibility at cutover, though, because from the
      read-path switch the declaration is what the predicate consults, and an
      over-declared task becomes *harder* to see than it is today. That is
      worth a line in the log, not a stopped migration.

    Written as two LEFT JOIN ... IS NULL counts rather than EXCEPT: EXCEPT is a
    syntax error on MySQL 8.0.27 (ERROR 1064; it arrived in 8.0.31), which is
    the version this deployment runs. Both directions verified against 8.0.27.

    Both are plain SELECTs, so unlike the backfill below they need no isolation
    change at all: measured against performance_schema.data_locks, this gate
    holds ZERO record locks at REPEATABLE READ and zero at READ COMMITTED. A
    non-locking consistent read is a snapshot read whatever the isolation, and
    that is the whole difference from the TaskProject migration, whose
    INSERT ... SELECT over these same six tables did have to be moved.
    """
    derived_not_declared = conn.execute(sa.text(f"""
        SELECT COUNT(*) FROM ({_DERIVED}) d
        LEFT JOIN TaskProject tp
               ON tp.TaskID = d.TaskID AND tp.ProjectID = d.ProjectID
        WHERE tp.TaskID IS NULL
    """)).scalar()
    if derived_not_declared:
        raise RuntimeError(
            f"{derived_not_declared} (task, project) pairs are reachable through "
            "the image links but not declared in TaskProject; "
            "fk_SubTaskImageLink_TaskProject would refuse them. Reconcile first."
        )

    declared_not_derived = conn.execute(sa.text(f"""
        SELECT COUNT(*) FROM TaskProject tp
        LEFT JOIN ({_DERIVED}) d
               ON d.TaskID = tp.TaskID AND d.ProjectID = tp.ProjectID
        WHERE d.TaskID IS NULL
    """)).scalar()
    if declared_not_derived:
        print(
            f"NOTE: {declared_not_derived} declared (task, project) pairs no link "
            "uses. Legal and fail-safe, but those tasks become less visible once "
            "the read path switches to the declaration."
        )


def _backfill(conn: Connection) -> None:
    """Copy SubTask.TaskID and ImageInstance.ProjectID onto every link row.

    Runs inside an autocommit block at READ COMMITTED, and both halves of that
    are load-bearing.

    What READ COMMITTED buys here is the GAP locks, and not -- measured -- the
    shared locks on the source rows. Counting performance_schema.data_locks
    for one 2,000-wide chunk against a 5,104-row stub: 12,127 record locks at
    REPEATABLE READ against 5,714 at READ COMMITTED, with every remaining lock
    a REC_NOT_GAP and the X,GAP entry on SubTaskImageLink gone. The 1,904
    shared record locks this statement takes on SubTask do NOT go away; a
    multi-table UPDATE reads its source tables under shared record locks at
    either isolation, and a session holding FOR UPDATE on one of those rows
    stalls this statement at both. That is worth stating plainly because the
    TaskProject migration's comment says the opposite about ITS statement and
    is right to: for INSERT ... SELECT, READ COMMITTED does drop the source
    locks entirely. The two shapes are not interchangeable, and the claim does
    not carry across.

    The gaps are still worth removing, and specifically worth it on this table.
    A gap lock on a SubTaskID range blocks inserts INTO that range, and unlike
    the ImageInstance backfill this one walks a column that is not
    AUTO_INCREMENT here -- see the chunking note below -- so a new link lands
    inside the range being walked rather than above it. The gap locks would
    block exactly the concurrent writes this migration is trying not to block.

    `SET SESSION transaction_isolation` only affects transactions that begin
    after it, and is accepted silently while one is already open. On a re-run
    the DDL above is skipped and the information_schema probes have left a
    transaction in progress, so a bare SET would verify green against a fresh
    database and silently take the full lock footprint on exactly the recovery
    path this migration is written to support. `autocommit_block()` is what
    guarantees no transaction is in progress on either path, and it commits
    through alembic's own transaction object rather than the connection --
    `conn.commit()` would deactivate the transaction alembic holds open, and
    the UPDATE of alembic_version after the last DDL would be lost at
    connection close, leaving the schema changed and the revision never
    stamped. The block alone is not enough either: AUTOCOMMIT changes
    transaction boundaries, not isolation. The isolation is put back explicitly
    at the end, because later migrations in the same `alembic upgrade` share
    this session and one left at READ COMMITTED would quietly change how they
    read.

    This needs row-based binary logging, which is what this deployment runs;
    InnoDB cannot statement-log at READ COMMITTED, so under
    binlog_format=STATEMENT the UPDATE fails with ERROR 1665 rather than
    logging something wrong.
    """
    with context.get_context().autocommit_block():
        # The block swaps in a connection at AUTOCOMMIT isolation, so the bind
        # has to be re-fetched here rather than reused from the caller.
        block_conn = op.get_bind()
        prior_isolation = block_conn.execute(
            sa.text("SELECT @@SESSION.transaction_isolation")
        ).scalar()
        block_conn.execute(
            sa.text("SET SESSION transaction_isolation = 'READ-COMMITTED'")
        )
        try:
            lo = block_conn.execute(
                sa.text("SELECT MIN(SubTaskID) FROM SubTaskImageLink")
            ).scalar()
            hi = block_conn.execute(
                sa.text("SELECT MAX(SubTaskID) FROM SubTaskImageLink")
            ).scalar()
            # 2,000 and not the 20,000 the ImageInstance migration uses: this
            # table is dense in SubTaskID. 87,454 rows sit in the range
            # 1..28,198, so a 20,000-wide window is two statements of ~44,000
            # rows each -- the opposite of chunking. Measured on dev.
            #
            # SubTaskID is also the leading column of the index InnoDB
            # clusters this table on. SubTaskImageLink declares no PRIMARY KEY,
            # so InnoDB promoted uq_SubTaskImageLink_SubTask_ImageIndex
            # (SubTaskID, ImageIndex) to the clustered index -- which is NOT
            # the (SubTaskID, ImageInstanceID) pair the model calls its primary
            # key. Chunking on SubTaskID therefore walks the clustered index in
            # order whichever of the two you believe, and each chunk is a
            # contiguous range rather than a scatter of secondary lookups.
            step = 2_000
            while lo is not None and lo <= hi:
                block_conn.execute(
                    sa.text("""
                        UPDATE SubTaskImageLink l
                          JOIN SubTask st ON st.SubTaskID = l.SubTaskID
                          JOIN ImageInstance ii
                            ON ii.ImageInstanceID = l.ImageInstanceID
                        SET l.TaskID = st.TaskID, l.ProjectID = ii.ProjectID
                        WHERE l.SubTaskID BETWEEN :lo AND :hi
                    """),
                    {"lo": lo, "hi": lo + step - 1},
                )
                lo += step
            # A closing unbounded sweep, where the ImageInstance and
            # Study/Series migrations instead re-read MAX and continued from
            # where they stopped. The difference is not style: SubTaskID is
            # AUTO_INCREMENT on SubTask but is a plain foreign key HERE, so a
            # row inserted while this loop runs -- a new image added to an
            # existing subtask -- lands at whatever SubTaskID that subtask
            # already had, which is anywhere in the range just walked and not
            # only above it. Continuing past `hi` would never see it. The
            # objection that made those migrations avoid this sweep was that
            # `WHERE ProjectID IS NULL` with no index on ProjectID scans and
            # X-locks the whole table, and that objection is correct: measured,
            # this statement holds ~15.3k record locks against a 5,104-row stub
            # at EITHER isolation -- READ COMMITTED does not help, because
            # every row matches. It is accepted rather than dodged. On 87,454
            # rows it is one table scan this migration can afford, it runs
            # inside the autocommit block so it commits and releases at once,
            # and it is the only statement here that can catch a link inserted
            # into the middle of the range the loop has already walked.
            block_conn.execute(
                sa.text("""
                    UPDATE SubTaskImageLink l
                      JOIN SubTask st ON st.SubTaskID = l.SubTaskID
                      JOIN ImageInstance ii
                        ON ii.ImageInstanceID = l.ImageInstanceID
                    SET l.TaskID = st.TaskID, l.ProjectID = ii.ProjectID
                    WHERE l.TaskID IS NULL OR l.ProjectID IS NULL
                """)
            )
        finally:
            # Read back rather than named literally, so this restores what the
            # session was actually on and not what the server default is
            # assumed to be.
            block_conn.execute(
                sa.text("SET SESSION transaction_isolation = :level"),
                {"level": prior_isolation},
            )


def upgrade() -> None:
    conn = op.get_bind()
    # Everything that can raise runs here, before the first ALTER: MySQL
    # commits DDL implicitly, so a guard that raises once ADD COLUMN has run
    # leaves the schema half changed.
    _require_fk_checks_on(conn)
    _require_strict_sql_mode(conn)
    _gate(conn)
    doomed = {
        column: _single_column_fk(conn, "SubTaskImageLink", column, parent)
        for column, parent in (
            ("SubTaskID", "SubTask"),
            ("ImageInstanceID", "ImageInstance"),
        )
    }

    if not _column_exists(conn, "SubTaskImageLink", "TaskID"):
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            "ADD COLUMN TaskID INT NULL, ADD COLUMN ProjectID INT NULL, "
            "ALGORITHM=INPLACE, LOCK=NONE"
        )
    _backfill(conn)
    # The block above swapped the bind; take a fresh one for the guards below.
    conn = op.get_bind()
    # Unguarded, because it is idempotent: MODIFY to the nullability a column
    # already has is accepted and changes nothing. It is also the only check
    # that the backfill missed no row, which is why `_require_strict_sql_mode`
    # ran before any of this.
    op.execute(
        "ALTER TABLE SubTaskImageLink "
        "MODIFY TaskID INT NOT NULL, MODIFY ProjectID INT NOT NULL, "
        "ALGORITHM=INPLACE, LOCK=NONE"
    )
    # The parent half of the first composite key. Redundant as a uniqueness
    # claim -- SubTaskID alone is already SubTask's primary key -- but InnoDB
    # will not let a foreign key reference (SubTaskID, TaskID) unless that
    # exact pair is itself a key. ImageInstance's and TaskProject's halves
    # already exist: uq_ImageInstance_Image_Project from the patient-chain
    # migration, and TaskProject's own primary key.
    if not _index_exists(conn, "SubTask", "uq_SubTask_SubTask_Task"):
        op.execute(
            "ALTER TABLE SubTask "
            "ADD UNIQUE INDEX uq_SubTask_SubTask_Task (SubTaskID, TaskID), "
            "ALGORITHM=INPLACE, LOCK=NONE"
        )
    # Built as one ALTER where several are missing so the table is rebuilt
    # once rather than three times, and clause by clause where a previous run
    # already created some. Online: index builds do not need the write window,
    # and asserting INPLACE/NONE is what keeps them out of it. Only the ADD
    # CONSTRAINT below is allowed to block writers.
    specs = [
        f"ADD INDEX {name} ({columns})"
        for name, columns in _NEW_INDEXES
        if not _index_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=INPLACE, LOCK=NONE"
        )
    # Added BEFORE the single-column keys they replace are dropped, so that at
    # no statement boundary is this table without a key to its parent. InnoDB
    # is perfectly willing to hold two foreign keys on one column -- the
    # ambiguity that forbids the end state is SQLAlchemy's mapper, which never
    # sees this intermediate. Dropped first, an interruption between the two
    # would leave a production table with neither and the operator with no
    # route back but hand repair, and the gap between them is precisely where
    # an interruption is most likely: the ADD is the slow statement of the
    # pair.
    #
    # COPY, not INPLACE: the in-place path is only available with
    # foreign_key_checks off, and then it does not check the rows already in
    # the table. This is the statement that needs the write window -- 1.7 s
    # for all three, measured.
    specs = [
        f"ADD CONSTRAINT {name} FOREIGN KEY ({columns}) "
        f"REFERENCES {parent} ({parent_columns})" + (f" {extra}" if extra else "")
        for name, columns, parent, parent_columns, extra in _NEW_FKS
        if not _fk_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=COPY, LOCK=SHARED"
        )
    # Online, and the reason the coexistence window is one statement wide
    # rather than one rebuild wide: dropping a foreign key is a metadata
    # change, so InnoDB neither copies the table nor blocks a writer for it.
    specs = [
        f"DROP FOREIGN KEY `{name}`" for name in doomed.values() if name is not None
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=INPLACE, LOCK=NONE"
        )
    specs = [
        f"DROP INDEX {name}"
        for name in _OLD_INDEXES
        if _index_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=INPLACE, LOCK=NONE"
        )


def downgrade() -> None:
    conn = op.get_bind()
    # Restoring a key is still adding a key, and a COPY rebuild with
    # foreign_key_checks off would restore one that has never looked at a row.
    _require_fk_checks_on(conn)
    # The old indexes come back FIRST, before the single-column keys that need
    # them. InnoDB binds a foreign key to the first index that can serve it,
    # and (SubTaskID, TaskID) can serve a single-column key on SubTaskID by
    # prefix; bound there, the DROP INDEX at the end would fail with ERROR
    # 1553. Restoring the narrow indexes first is not enough on its own to
    # decide the binding, so the drop below is ordered after the composite keys
    # are gone, when the narrow index is the only remaining candidate.
    specs = [
        f"ADD INDEX {name} ({columns})"
        for name, columns in (
            ("ix_SubTaskImageLink_Image_SubTask", "ImageInstanceID, SubTaskID"),
            ("fk_SubTaskImageLink_SubTask1_idx", "SubTaskID"),
            ("fk_SubTaskImageLink_ImageInstance1_idx", "ImageInstanceID"),
        )
        if not _index_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=INPLACE, LOCK=NONE"
        )
    # Add before drop, for the reason `upgrade` does: at no boundary in here is
    # the table left without a key to its parent either.
    #
    # Not an exact inverse. The original names came from the schema this
    # repository inherited and are not recoverable once dropped, so the
    # restored keys are given names of this migration's own; anything that
    # reads them by name -- there is nothing today -- would have to be told.
    # ON UPDATE is deliberately not carried back: the keys this replaced had
    # only ON DELETE CASCADE.
    specs = [
        f"ADD CONSTRAINT {name} FOREIGN KEY ({column}) "
        f"REFERENCES {parent} ({parent_column}) ON DELETE CASCADE"
        for name, column, parent, parent_column in (
            ("fk_SubTaskImageLink_SubTask_single", "SubTaskID",
             "SubTask", "SubTaskID"),
            ("fk_SubTaskImageLink_Image_single", "ImageInstanceID",
             "ImageInstance", "ImageInstanceID"),
        )
        if not _fk_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=COPY, LOCK=SHARED"
        )
    specs = [
        f"DROP FOREIGN KEY {name}"
        for name, *_rest in _NEW_FKS
        if _fk_exists(conn, "SubTaskImageLink", name)
    ]
    if specs:
        op.execute(
            "ALTER TABLE SubTaskImageLink "
            + ", ".join(specs)
            + ", ALGORITHM=INPLACE, LOCK=NONE"
        )
    # The columns go with their indexes, in one statement: DROP COLUMN would
    # be refused while an index still names the column, and dropping the
    # indexes in a statement of their own would leave a boundary at which the
    # table carries two unindexed NOT NULL columns nothing maintains.
    specs = [
        f"DROP INDEX {name}"
        for name, _columns in _NEW_INDEXES
        if _index_exists(conn, "SubTaskImageLink", name)
    ]
    specs += [
        f"DROP COLUMN {column}"
        for column in ("TaskID", "ProjectID")
        if _column_exists(conn, "SubTaskImageLink", column)
    ]
    if specs:
        op.execute("ALTER TABLE SubTaskImageLink " + ", ".join(specs))
    if _index_exists(conn, "SubTask", "uq_SubTask_SubTask_Task"):
        op.execute(
            "ALTER TABLE SubTask DROP INDEX uq_SubTask_SubTask_Task, "
            "ALGORITHM=INPLACE, LOCK=NONE"
        )
