"""add TaskProject

Revision ID: 99724789b34d
Revises: 4eae42457fa2
Create Date: 2026-08-20

Creates the declaration table: the projects a task may contain, stated
directly rather than derived by walking every image up to its patient's
project. Later tasks add the foreign keys that hold data inside this
declaration; this migration only creates the table and seeds it from what
each task currently derives.

Not autogenerated. This worktree has no dev/.env or dev/.env.alembic, and the
DDL grant this migration needs only works from inside the compose network --
not from the host, not via `docker exec` -- so `alembic revision
--autogenerate` could not be run here. Hand-authored to match the shape
autogenerate would produce; a human should diff this against a live schema
before it is trusted unreviewed.

No strict-SQL-mode guard, unlike its two predecessors. That guard exists to
catch a NOT NULL conversion silently rewriting a missed row to 0 -- relevant
when a column is added nullable, backfilled by UPDATE, and only then
tightened with `MODIFY ... NOT NULL`. TaskID and ProjectID here are never
nullable: they are the table's primary key, declared NOT NULL at CREATE TABLE
time, and the backfill below is an INSERT of brand-new rows, not an UPDATE of
existing ones. There is no tightening step for the guard to protect.

No chunking, unlike its two predecessors. Those backfills rewrite 1.85M and
several hundred thousand rows respectively and are chunked specifically to
avoid holding row locks on a live, populated table for tens of seconds. This
one inserts on the order of 108 rows, computed by a single indexed join and
written to a table that has no rows and no readers yet (it does not exist
until this same migration creates it) -- chunking machinery here would be
noise with nothing to protect against.

The backfill is deliberately plain DML in the ambient migration transaction,
not wrapped in `context.get_context().autocommit_block()`. Both DDL
statements below (CREATE TABLE, CREATE INDEX) run and implicitly commit
before the INSERT is ever sent, so the only way this function can be
re-entered by a re-run is if the process died before the INSERT's surrounding
transaction committed -- in which case the INSERT was never durable and the
table is empty again. That makes a bare `INSERT ... SELECT` safe without an
`INSERT IGNORE` or a duplicate check: either it lands together with the
alembic_version stamp in one commit, or it does not land at all.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Connection


# revision identifiers, used by Alembic.
revision: str = '99724789b34d'
down_revision: Union[str, None] = '4eae42457fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(conn: Connection, table: str) -> bool:
    """Make CREATE TABLE re-runnable. MySQL has no CREATE TABLE IF NOT EXISTS via op.create_table."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t"
            ),
            {"t": table},
        ).scalar()
    )


def _index_exists(conn: Connection, table: str, index: str) -> bool:
    """Make CREATE INDEX re-runnable. MySQL has no CREATE INDEX IF NOT EXISTS."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.STATISTICS "
                "WHERE TABLE_SCHEMA = DATABASE() "
                "AND TABLE_NAME = :t AND INDEX_NAME = :i"
            ),
            {"t": table, "i": index},
        ).scalar()
    )


def upgrade() -> None:
    conn = op.get_bind()
    # DDL commits implicitly in MySQL, so a half-applied run (table created,
    # index not yet created, or vice versa) must be resumable without erroring
    # on "table already exists" / duplicate index. Guarded individually, in
    # the order they are created, so a re-run picks up wherever it stopped.
    if not _table_exists(conn, "TaskProject"):
        op.create_table(
            "TaskProject",
            sa.Column("TaskID", sa.Integer(), nullable=False),
            sa.Column("ProjectID", sa.Integer(), nullable=False),
            sa.Column(
                "DateInserted",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["TaskID"], ["Task.TaskID"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(
                ["ProjectID"], ["Project.ProjectID"], ondelete="RESTRICT"
            ),
            sa.PrimaryKeyConstraint("TaskID", "ProjectID"),
        )
    # Named explicitly: InnoDB requires an index on the referencing side of
    # the ProjectID foreign key and creates one itself, called `ProjectID`, if
    # this one is missing. That index is undeclarable in the ORM model and
    # undroppable in the database (ERROR 1553: "needed in a foreign key
    # constraint"), so confirm it exists under the name the model gives it.
    if not _index_exists(conn, "TaskProject", "ix_TaskProject_Project"):
        op.create_index(
            "ix_TaskProject_Project", "TaskProject", ["ProjectID"], unique=False
        )

    # The declaration seeded from what each task currently derives: the set
    # of projects reached by walking every image a task's subtasks reference,
    # up through Series and Study, to the patient's project. This is the one
    # moment the derived and declared answers must agree; a later task
    # asserts that before any constraint goes on top of this table.
    #
    # Deliberately does not filter ImageInstance.Inactive: a soft-deleted
    # image still ties its project to the task, and excluding it would narrow
    # the declaration below what the (still-present) links require -- the
    # same reasoning as the walk this replaces.
    op.execute("""
        INSERT INTO TaskProject (TaskID, ProjectID)
        SELECT DISTINCT st.TaskID, p.ProjectID
        FROM SubTask st
          JOIN SubTaskImageLink sil ON sil.SubTaskID = st.SubTaskID
          JOIN ImageInstance ii ON ii.ImageInstanceID = sil.ImageInstanceID
          JOIN Series se ON se.SeriesID = ii.SeriesID
          JOIN Study sy ON sy.StudyID = se.StudyID
          JOIN Patient p ON p.PatientID = sy.PatientID
    """)


def downgrade() -> None:
    # DROP TABLE removes its indexes with it, so there is nothing for a
    # separate DROP INDEX to do here; guarding the table drop alone is
    # sufficient to make this re-runnable.
    conn = op.get_bind()
    if _table_exists(conn, "TaskProject"):
        op.drop_table("TaskProject")
