"""update image storage

Revision ID: 533b4abe81b9
Revises: e4247389063f
Create Date: 2026-02-05 16:36:10.858485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from eyened_orm.image_instance import _make_public_id

# revision identifiers, used by Alembic.
revision: str = '533b4abe81b9'
down_revision: Union[str, None] = 'e4247389063f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_backends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=256), nullable=False),
    sa.Column('config', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "INSERT INTO storage_backends (id, `key`, `kind`, `config`) "
            "VALUES (1, 'default', 'local', '{}')"
        )
    )


    op.add_column('ImageInstance', sa.Column('public_id', sa.String(length=12), nullable=True))
    op.add_column('ImageInstance', sa.Column('storage_backend_id', sa.Integer(), nullable=True))
    op.add_column('ImageInstance', sa.Column('object_prefix', sa.String(length=256), nullable=True))
    op.add_column('ImageInstance', sa.Column('object_key', sa.String(length=256), nullable=False))

    connection.execute(
        sa.text("UPDATE ImageInstance SET storage_backend_id = 1")
    )
    image_instance = sa.Table(
        'ImageInstance',
        sa.MetaData(),
        sa.Column('ImageInstanceID', sa.Integer()),
        sa.Column('public_id', sa.String(length=12)),
    )
    # Count how many ImageInstance rows we need public_ids for.
    total_needed = connection.execute(
        sa.select(sa.func.count(image_instance.c.ImageInstanceID))
    ).scalar_one()

    # Pre-generate that many unique public_ids, using a set to ensure uniqueness.
    public_ids: set[str] = set()
    while len(public_ids) < total_needed:
        public_ids.add(_make_public_id())

    public_id_iter = iter(public_ids)

    # Now assign them in batches for efficient updates.
    result = connection.execute(sa.select(image_instance.c.ImageInstanceID))
    update_stmt = image_instance.update().where(
        image_instance.c.ImageInstanceID == sa.bindparam("b_ImageInstanceID")
    ).values(public_id=sa.bindparam("public_id"))
    batch_size = 1000
    while True:
        rows = result.fetchmany(batch_size)
        if not rows:
            break

        params = [
            {
                "b_ImageInstanceID": image_id,
                "public_id": next(public_id_iter),
            }
            for (image_id,) in rows
        ]
        connection.execute(update_stmt, params)
    op.alter_column('ImageInstance', 'public_id',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.alter_column('ImageInstance', 'storage_backend_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'ImageInstance', ['public_id'])
    op.create_index('ix_ImageInstance_public_id', 'ImageInstance', ['public_id'], unique=True)
    op.create_foreign_key(None, 'ImageInstance', 'storage_backends', ['storage_backend_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ImageInstance', type_='foreignkey')
    op.drop_index('ix_ImageInstance_public_id', table_name='ImageInstance')
    op.drop_constraint(None, 'ImageInstance', type_='unique')
    op.alter_column('ImageInstance', 'storage_backend_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ImageInstance', 'public_id',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.drop_table('storage_backends')
    # ### end Alembic commands ###
