"""composite FKs down the patient chain

Revision ID: b45090e1544e
Revises: 99724789b34d
Create Date: 2026-08-20

Makes the denormalized ProjectID copies structurally true rather than true by
convention. Each of Study, Series and ImageInstance gets a composite foreign
key carrying ProjectID alongside the key it already had, and after this the
database itself refuses to let a child's project drift from its parent's.

Each composite key REPLACES the single-column foreign key on the same column
rather than joining it. Two foreign-key paths between the same pair of tables
make SQLAlchemy refuse to configure the relationship (AmbiguousForeignKeysError)
and nothing imports; the replacement is also what makes the ORM copy ProjectID
parent-to-child during a flush.

The replacement is done ADD first, DROP second, so per table the two keys
coexist for exactly one statement. That order is the point, not an accident.
InnoDB is perfectly willing to hold two foreign keys on the same column -- the
ambiguity that forbids the end state is SQLAlchemy's mapper, which never sees
this intermediate -- and adding first is the only order in which the table is
never, at any statement boundary, without a key to its parent. Dropped first,
an interruption between the two would leave a production table with neither,
and the operator with no route back but hand-repair; and the gap between the
two is precisely where an interruption is most likely: the ADD is the slow
statement of the pair, the rebuild measured at roughly 33 s per 1.85M rows,
and so the one that times out.

Not autogenerated. This worktree has no dev/.env or dev/.env.alembic, and the
DDL grant this migration needs only works from inside the compose network --
not from the host, not via `docker exec` -- so `alembic revision
--autogenerate` could not be run here. Hand-authored to match the shape
autogenerate would produce, then parsed and executed end to end against a
throwaway MySQL 8.0.27 (upgrade, re-run, downgrade, re-run, upgrade again) on a
stub of the pre-migration schema. A human should still diff it against the live
schema before it is trusted unreviewed.

No strict-SQL-mode guard, unlike two of its predecessors. That guard protects a
`MODIFY ... NOT NULL` tightening from silently rewriting a missed row to 0.
This migration adds no column and tightens no nullability; the only thing it
needs the server to be honest about is foreign_key_checks, which is asserted
directly below.

Every index and constraint name below is copied from the model's __table_args__
verbatim. A name derived from the column instead would differ by a word
("ix_Study_PatientID_Project" vs the model's "ix_Study_Patient_Project") and the
next autogenerate would emit a spurious drop-and-add for each one.

Re-runnable, like its two predecessors and for the same reason: MySQL commits
DDL implicitly, so the ten statements below commit one at a time and an
interrupted run -- a crash, a timeout on one of the rebuilds, or an operator
recovery (`alembic stamp <down_revision>` then `alembic upgrade head`) -- can
re-enter this function with any prefix of them already applied. Each step is
guarded by the state it would produce, so a re-run picks up wherever it stopped
instead of dying on ERROR 1061 (duplicate index) and stranding the chain
half-converted. Nothing that can raise runs after the first ALTER: the one
check that could still fail on a well-formed database happens in a discovery
pass before any DDL. Verified by killing the run at each of the ten statement
boundaries and re-running from there. Downgrade is built and verified the same
way, in both respects.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Connection


# revision identifiers, used by Alembic.
revision: str = 'b45090e1544e'
down_revision: Union[str, None] = '99724789b34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The three tables in the order they must be converted: a child's composite
# foreign key needs its parent's (pk, ProjectID) unique index to exist first,
# and each table here is the next one's parent.
#
# (table, pk, column, parent, parent_pk, uq, ix, fk)
_CHAIN = (
    ("Study", "StudyID", "PatientID", "Patient", "PatientID",
     "uq_Study_Study_Project", "ix_Study_Patient_Project",
     "fk_Study_Patient_Project"),
    ("Series", "SeriesID", "StudyID", "Study", "StudyID",
     "uq_Series_Series_Project", "ix_Series_Study_Project",
     "fk_Series_Study_Project"),
    ("ImageInstance", "ImageInstanceID", "SeriesID", "Series", "SeriesID",
     "uq_ImageInstance_Image_Project", "ix_ImageInstance_Series_Project",
     "fk_ImageInstance_Series_Project"),
)


# Deliberately copied from the sibling migrations rather than imported: a
# migration that imports from another one breaks the moment that other file is
# squashed away.
def _index_exists(conn: Connection, table: str, index: str) -> bool:
    """Make ADD INDEX re-runnable. MySQL has no ADD INDEX IF NOT EXISTS."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.STATISTICS "
                "WHERE TABLE_SCHEMA = DATABASE() "
                "AND TABLE_NAME = :t AND INDEX_NAME = :i"
            ),
            {"t": table, "i": index},
        ).scalar()
    )


def _fk_exists(conn: Connection, table: str, name: str) -> bool:
    """Make ADD CONSTRAINT / DROP FOREIGN KEY re-runnable, by constraint name."""
    return bool(
        conn.execute(
            sa.text(
                "SELECT 1 FROM information_schema.TABLE_CONSTRAINTS "
                "WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = :t "
                "AND CONSTRAINT_NAME = :n AND CONSTRAINT_TYPE = 'FOREIGN KEY'"
            ),
            {"t": table, "n": name},
        ).scalar()
    )


def _single_column_fk(
    conn: Connection, table: str, column: str, referenced: str
) -> Union[str, None]:
    """Name the single-column FK the composite replaces. Reads only.

    Names come from the original schema (`Study_ibfk_1`, `Series_ibfk_1`,
    `fk_ImageInstance_Series1`), not from the models, so they are discovered
    rather than hardcoded.

    Restricted to constraints of exactly ONE column, which is load-bearing
    rather than defensive: the composite this migration adds is created BEFORE
    this one is dropped and shares its COLUMN_NAME *and* its
    REFERENCED_TABLE_NAME, so without `c.cols = 1` the query matches both keys
    and the drop could take the new one.

    Returns None when there is nothing to drop -- a re-run that already got
    past the drop, or a table that arrived without the key. Neither is an
    error, and they need not be told apart: this migration's answer to both is
    the same, add the composite and drop nothing. Two or more candidates is an
    error, because no rule here could pick between them. Emitting no DDL is
    what lets `upgrade` call this for all three tables up front and take that
    error while the schema is still whole.
    """
    names = (
        conn.execute(
            sa.text("""
                SELECT k.CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE k
                JOIN (
                    SELECT CONSTRAINT_SCHEMA, CONSTRAINT_NAME, COUNT(*) AS cols
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t
                    GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_NAME
                ) c
                  ON c.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
                 AND c.CONSTRAINT_NAME = k.CONSTRAINT_NAME
                WHERE k.TABLE_SCHEMA = DATABASE() AND k.TABLE_NAME = :t
                  AND k.COLUMN_NAME = :c AND k.REFERENCED_TABLE_NAME = :r
                  AND c.cols = 1
            """),
            {"t": table, "c": column, "r": referenced},
        )
        .scalars()
        .all()
    )
    if len(names) > 1:
        raise RuntimeError(
            f"expected at most one single-column FK on {table}.{column} -> "
            f"{referenced}, found {names!r}"
        )
    return names[0] if names else None


def _require_fk_checks_on(conn: Connection) -> None:
    """A COPY rebuild only validates existing rows while this is on.

    With it off, MySQL adds the constraint over data that violates it, the bad
    rows survive, and CHECK TABLE reports OK -- a constraint that lies about
    everything already in the table, with nothing that would ever surface it.
    Asserted by `downgrade` too: the keys it restores are narrower, but they
    are still keys, and a downgrade that quietly declined to check them would
    hand back a database whose foreign keys mean nothing.
    """
    if not conn.execute(sa.text("SELECT @@foreign_key_checks")).scalar():
        raise RuntimeError(
            "foreign_key_checks is off; ADD FOREIGN KEY would create the "
            "constraint without checking a single existing row"
        )


def upgrade() -> None:
    conn = op.get_bind()
    _require_fk_checks_on(conn)
    # Discovered for all three tables here, before the first ALTER, because
    # `_single_column_fk` is the only thing below that can raise on a
    # well-formed database. Doing it up front is what keeps that failure from
    # landing between two of the statements, where it would abort a run that
    # has already changed the schema.
    doomed = {
        table: _single_column_fk(conn, table, column, parent)
        for table, _pk, column, parent, *_rest in _CHAIN
    }
    # The parent half of Study's composite key. Redundant as a uniqueness
    # claim -- PatientID alone is already the primary key -- but InnoDB will
    # not let a foreign key reference (PatientID, ProjectID) unless that exact
    # pair is itself a key.
    if not _index_exists(conn, "Patient", "uq_Patient_Patient_Project"):
        op.execute(
            "ALTER TABLE Patient "
            "ADD UNIQUE INDEX uq_Patient_Patient_Project (PatientID, ProjectID), "
            "ALGORITHM=INPLACE, LOCK=NONE"
        )
    for table, pk, column, parent, parent_pk, uq, ix, fk in _CHAIN:
        # Three ordering constraints, and the three statements below satisfy
        # all of them -- do not fold or resequence them:
        #
        #  - the unique index on the PARENT must exist before the child's
        #    foreign key is added, because InnoDB requires the referenced
        #    columns to be a key. The parent's index was created either by the
        #    Patient statement above or by this loop's previous iteration.
        #  - the child's own composite index must exist before the composite
        #    FK is added, or InnoDB creates one itself under a generated name
        #    that no later migration can predict.
        #  - the composite FK must be added before the single-column key it
        #    replaces is dropped, so that no interruption can leave the table
        #    with neither -- see this module's docstring.
        #
        # Built as one ALTER where both are missing so the table is rebuilt
        # once rather than twice, and clause by clause where a previous run
        # already created one of them.
        specs = []
        if not _index_exists(conn, table, uq):
            specs.append(f"ADD UNIQUE INDEX {uq} ({pk}, ProjectID)")
        if not _index_exists(conn, table, ix):
            specs.append(f"ADD INDEX {ix} ({column}, ProjectID)")
        if specs:
            # Online: these index builds do not need the write window, and
            # asserting INPLACE/NONE here is what keeps them out of it. Only
            # the ADD CONSTRAINT below is allowed to block writers.
            op.execute(
                f"ALTER TABLE {table} "
                + ", ".join(specs)
                + ", ALGORITHM=INPLACE, LOCK=NONE"
            )
        if not _fk_exists(conn, table, fk):
            # COPY, not INPLACE: the in-place path is only available with
            # foreign_key_checks off, and then it does not check the rows
            # already in the table. This is the statement that needs the write
            # window -- roughly 33 s per 1.85M rows, measured.
            op.execute(
                f"ALTER TABLE {table} ADD CONSTRAINT {fk} "
                f"FOREIGN KEY ({column}, ProjectID) "
                f"REFERENCES {parent} ({parent_pk}, ProjectID) "
                "ON UPDATE CASCADE ON DELETE CASCADE, "
                "ALGORITHM=COPY, LOCK=SHARED"
            )
        if doomed[table] is not None:
            # Online, and the reason the coexistence window is one statement
            # wide rather than one rebuild wide: dropping a foreign key is a
            # metadata change, so InnoDB neither copies the table nor blocks a
            # writer for it. The single-column INDEX the key used
            # (`fk_Study_Patient1_idx` and its siblings) is NOT dropped with
            # it, here or anywhere; `downgrade` needs it.
            op.execute(
                f"ALTER TABLE {table} DROP FOREIGN KEY `{doomed[table]}`, "
                "ALGORITHM=INPLACE, LOCK=NONE"
            )


def downgrade() -> None:
    conn = op.get_bind()
    # Restoring a key is still adding a key, and a COPY rebuild with
    # foreign_key_checks off would restore one that has never looked at a row.
    _require_fk_checks_on(conn)
    # Reverse order: a parent's (pk, ProjectID) unique index cannot be dropped
    # while its child's composite key still references it, so each child is
    # unwound before its parent.
    for table, _pk, column, parent, parent_pk, uq, ix, fk in reversed(_CHAIN):
        # Add before drop, for the reason `upgrade` does: at no boundary in
        # here is the table left without a key to its parent either.
        #
        # Not an exact inverse: the original names (`Study_ibfk_1`,
        # `Series_ibfk_1`, `fk_ImageInstance_Series1`) came from the schema
        # this repository inherited and are not recoverable once dropped, so
        # the restored key is given a name of this migration's own. Anything
        # that reads it by name -- there is nothing today -- would have to be
        # told. ON UPDATE is deliberately not carried back: the keys this
        # replaces had only ON DELETE CASCADE.
        restored = f"fk_{table}_{parent}_single"
        if not _fk_exists(conn, table, restored):
            # COPY/SHARED for the same reason as the upgrade's ADD, and stated
            # for the same reason: this is the write-blocking statement of the
            # three, and an operator reading this file mid-incident should not
            # have to know that MySQL would have picked COPY anyway.
            op.execute(
                f"ALTER TABLE {table} ADD CONSTRAINT {restored} "
                f"FOREIGN KEY ({column}) REFERENCES {parent} ({parent_pk}) "
                "ON DELETE CASCADE, ALGORITHM=COPY, LOCK=SHARED"
            )
        if _fk_exists(conn, table, fk):
            op.execute(
                f"ALTER TABLE {table} DROP FOREIGN KEY {fk}, "
                "ALGORITHM=INPLACE, LOCK=NONE"
            )
        # Dropped after the single-column key is restored, which is safe only
        # because InnoDB binds that key to the pre-existing single-column index
        # (`fk_Study_Patient1_idx` and its siblings) rather than to
        # (column, ProjectID) -- it takes the first index that can serve the
        # key, and those were created first. Bound the other way it would need
        # this index and the drop would fail with ERROR 1553. Verified on
        # 8.0.27 for all three tables rather than assumed; if a future schema
        # ever loses those single-column indexes, this order stops working.
        specs = [
            f"DROP INDEX {name}"
            for name in (uq, ix)
            if _index_exists(conn, table, name)
        ]
        if specs:
            op.execute(
                f"ALTER TABLE {table} "
                + ", ".join(specs)
                + ", ALGORITHM=INPLACE, LOCK=NONE"
            )
    if _index_exists(conn, "Patient", "uq_Patient_Patient_Project"):
        op.execute(
            "ALTER TABLE Patient DROP INDEX uq_Patient_Patient_Project, "
            "ALGORITHM=INPLACE, LOCK=NONE"
        )
