"""remove ModelSegmentation ReferenceSegmentationID

Revision ID: 590cff943534
Revises: 533b4abe81b9
Create Date: 2026-02-24 16:16:15.221586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '590cff943534'
down_revision: Union[str, None] = '533b4abe81b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ModelSegmentation_ibfk_3', 'ModelSegmentation', type_='foreignkey')
    op.drop_column('ModelSegmentation', 'ReferenceSegmentationID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ModelSegmentation', sa.Column('ReferenceSegmentationID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ModelSegmentation_ibfk_3', 'ModelSegmentation', 'Segmentation', ['ReferenceSegmentationID'], ['SegmentationID'])
    # ### end Alembic commands ###
