"""added datetimes for tracking inserts updates

Revision ID: b9ef1a76ec71
Revises: efb725a49704
Create Date: 2024-10-10 13:03:30.371184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9ef1a76ec71'
down_revision = 'efb725a49704'
branch_labels = None
depends_on = None


def upgrade() -> None:

    
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE Annotation SET Created = NOW() WHERE Created IS NULL")
    op.alter_column('Annotation', 'Created', existing_type=sa.DateTime(), server_default=sa.func.current_timestamp(), new_column_name='DateInserted', nullable=False)
    op.execute("UPDATE AnnotationData SET Modified = NOW() WHERE Modified IS NULL")
    op.alter_column('AnnotationData', 'Modified', existing_type=sa.DateTime(), server_default=sa.func.current_timestamp(), server_onupdate=sa.func.current_timestamp(), new_column_name='DateModified')

    op.add_column('Creator', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('Feature', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))

    op.execute("UPDATE FormAnnotation SET Created = NOW() WHERE Created IS NULL")
    op.execute("UPDATE FormAnnotation SET Modified = NOW() WHERE Modified IS NULL")
    op.alter_column('FormAnnotation', 'Modified', existing_type=sa.DateTime(), server_default=sa.func.current_timestamp(), server_onupdate=sa.func.current_timestamp(), new_column_name='DateModified', nullable=False)
    op.alter_column('FormAnnotation', 'Created', existing_type=sa.DateTime(), server_default=sa.func.current_timestamp(), new_column_name='DateInserted', nullable=False)
    op.alter_column('FormAnnotation', 'DateModified',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.add_column('ImageInstance', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('ImageInstance', sa.Column('DateModified', sa.DateTime(), server_default=sa.func.current_timestamp(), server_onupdate=sa.func.current_timestamp(), nullable=True))
    op.add_column('ImageInstance', sa.Column('DatePreprocessed', sa.DateTime(), nullable=True))

    op.add_column('Patient', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('Project', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('Study', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('Task', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('TaskDefinition', sa.Column('DateInserted', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=False))
    # # ### end Alembic commands ###