"""fundus bounds, keypoints and quality

Revision ID: efb725a49704
Revises: 3b53d030fb6a
Create Date: 2024-10-09 19:20:43.904293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efb725a49704'
down_revision = '3b53d030fb6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ROI -> CFI_ROI
    op.alter_column('ImageInstance', 'ROI', existing_type=sa.JSON(), new_column_name='CFROI')
    # Keypoints -> CFI_Keypoints
    op.alter_column('ImageInstance', 'Keypoints', existing_type=sa.JSON(), new_column_name='CFKeypoints')
    # Add CFI_Quality
    op.add_column('ImageInstance', sa.Column('CFQuality', sa.Float(), nullable=True))
    # ### end Alembic commands ###


