"""mysqlwb_idx_uq_harmonization

Revision ID: fbca4c2617b0
Revises: e5d9bb4214cb
Create Date: 2024-09-20 15:23:06.154586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbca4c2617b0'
down_revision = 'e5d9bb4214cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Project
    op.drop_index('Project_ProjectName_UNIQUE', table_name='Project')
    op.create_unique_constraint(op.f('ProjectName_UNIQUE'), 'Project', ['ProjectName'])

    # Patient
    op.create_index('fk_Patient_Project1_idx', 'Patient', ['ProjectID'], unique=False)
    op.drop_index('ProjectID', table_name='Patient')

    # Study
    op.create_index('fk_Study_Patient1_idx', 'Study', ['PatientID'], unique=False)
    op.drop_index('PatientID', table_name='Study')

    # Series
    op.create_index('fk_Series_Study1_idx', 'Series', ['StudyID'], unique=False)
    op.drop_index('StudyID', table_name='Series')


    #ImageInstance
    op.create_index('fk_ImageInstance_Device1_idx', 'ImageInstance', ['DeviceID'], unique=False)
    op.drop_index('DeviceID', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_Modality1_idx', 'ImageInstance', ['ModalityID'], unique=False)
    op.drop_index('ModalityID', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_Scan1_idx', 'ImageInstance', ['ScanID'], unique=False)
    op.drop_index('ScanID', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_Series1_idx', 'ImageInstance', ['SeriesID'], unique=False)
    op.drop_index('SeriesID', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_SourceInfo1_idx', 'ImageInstance', ['SourceInfoID'], unique=False)
    op.drop_index('SourceInfoID', table_name='ImageInstance')


    # Annotation 
    op.create_index('fk_Annotation_AnnotationType1_idx', 'Annotation', ['AnnotationTypeID'], unique=False)
    op.drop_index('AnnotationTypeID', table_name='Annotation')
    op.create_index('fk_Annotation_Creator1_idx', 'Annotation', ['CreatorID'], unique=False)
    op.drop_index('CreatorID', table_name='Annotation')
    op.create_index('fk_Annotation_Feature1_idx', 'Annotation', ['FeatureID'], unique=False)
    op.drop_index('FeatureID', table_name='Annotation')
    op.create_index('fk_Annotation_ImageInstance1_idx', 'Annotation', ['ImageInstanceID'], unique=False)
    op.drop_index('ImageInstanceID', table_name='Annotation')
    op.create_index('fk_Annotation_Study1_idx', 'Annotation', ['StudyID'], unique=False)
    op.drop_index('StudyID', table_name='Annotation')
    op.drop_index('AnnotationData_DatasetIdentifier_UNIQUE', table_name='AnnotationData')
    op.create_unique_constraint(op.f('DatasetIdentifier_UNIQUE'), 'AnnotationData', ['DatasetIdentifier'])
    op.create_index('fk_Annotation_Patient1_idx', 'Annotation', ['PatientID'], unique=False)
    op.drop_index('PatientID', table_name='Annotation')
    op.create_index('fk_Annotation_Series1_idx', 'Annotation', ['SeriesID'], unique=False)
    op.drop_index('SeriesID', table_name='Annotation')
    

    # AnnotationData
    op.create_index('fk_AnnotationData_Annotation1_idx', 'AnnotationData', ['AnnotationID'], unique=False)
    op.drop_index('AnnotationID', table_name='AnnotationData')


    # AnnotationTag
    op.create_index('fk_AnnotationTag_Annotation1_idx', 'AnnotationTag', ['AnnotationID'], unique=False)
    op.drop_index('AnnotationID', table_name='AnnotationTag')
    op.create_index('fk_AnnotationTag_Tag1_idx', 'AnnotationTag', ['TagID'], unique=False)
    op.drop_index('TagID', table_name='AnnotationTag')


    # StudyTag
    op.create_index('fk_StudyTag_Study1_idx', 'StudyTag', ['StudyID'], unique=False)
    op.drop_index('StudyID', table_name="StudyTag")
    op.create_index('fk_StudyTag_Tag1_idx', 'StudyTag', ['TagID'], unique=False)
    op.drop_index('TagID', table_name="StudyTag")


    # ImageInstanceTag
    op.create_index('fk_ImageInstanceTag_ImageInstance1_idx', 'ImageInstanceTag', ['ImageInstanceID'], unique=False)
    op.drop_index('ImageInstanceID', table_name='ImageInstanceTag')
    op.create_index('fk_ImageInstanceTag_Tag1_idx', 'ImageInstanceTag', ['TagID'], unique=False)
    op.drop_index('TagID', table_name='ImageInstanceTag')


    # Task
    op.create_index('fk_Task_TaskDefinition1_idx', 'Task', ['TaskDefinitionID'], unique=False)
    op.drop_index('TaskDefinitionID', table_name="Task")
    op.create_index('fk_Task_TaskState1_idx', 'Task', ['TaskStateID'], unique=False)
    op.drop_index('TaskStateID', table_name="Task")


    # SubTask
    op.create_index('fk_SubTask_Creator1_idx', 'SubTask', ['CreatorID'], unique=False)
    op.drop_index('CreatorID', table_name='SubTask')
    op.create_index('fk_SubTask_Task1_idx', 'SubTask', ['TaskID'], unique=False)
    op.drop_index('TaskID', table_name='SubTask')
    op.create_index('fk_SubTask_TaskState1_idx', 'SubTask', ['TaskStateID'], unique=False)
    op.drop_index('TaskStateID', table_name='SubTask')


    # SubTaskImageLink
    op.create_index('fk_SubTaskImageLink_ImageInstance1_idx', 'SubTaskImageLink', ['ImageInstanceID'], unique=False)
    op.drop_index('ImageInstanceID', table_name='SubTaskImageLink')
    op.create_index('fk_SubTaskImageLink_SubTask1_idx', 'SubTaskImageLink', ['SubTaskID'], unique=False)
    op.drop_index('SubTaskID', table_name='SubTaskImageLink')


    # UNIQUE Creator, Feature, FormSchema, ImageInstance
    op.drop_index('Creator_CreatorName_UNIQUE', table_name='Creator')
    op.create_unique_constraint(op.f('CreatorName_UNIQUE'), 'Creator', ['CreatorName'])
    op.drop_index('Feature_FeatureName_UNIQUE', table_name='Feature')
    op.create_unique_constraint(op.f('FeatureName_UNIQUE'), 'Feature', ['FeatureName'])
    op.drop_index('FormSchema_SchemaName_UNIQUE', table_name='FormSchema')
    op.create_unique_constraint(op.f('SchemaName_UNIQUE'), 'FormSchema', ['SchemaName'])
    op.drop_index('ImageInstance_SOPInstanceUid_UNIQUE', table_name='ImageInstance')
    op.create_unique_constraint(op.f('SOPInstanceUid_UNIQUE'), 'ImageInstance', ['SOPInstanceUid'])

    # UNIQUE Modality
    op.drop_index('Modality_ModalityTag_UNIQUE', table_name='Modality')
    op.create_unique_constraint(op.f('ModalityTag_UNIQUE'), 'Modality', ['ModalityTag'])

    # UNIQUE Scan, Series
    op.drop_index('Scan_ScanMode_UNIQUE', table_name='Scan')
    op.create_unique_constraint(op.f('ScanMode_UNIQUE'), 'Scan', ['ScanMode'])
    op.drop_index('Series_SeriesInstanceUid_UNIQUE', table_name='Series')
    op.create_unique_constraint(op.f('SeriesInstanceUid_UNIQUE'), 'Series', ['SeriesInstanceUid'])

    # UNIQUE SourceInfo, Study, Tag
    op.drop_index('SourceInfo_SourceName_UNIQUE', table_name='SourceInfo')
    op.drop_index('SourceInfo_SourcePath_UNIQUE', table_name='SourceInfo')
    op.drop_index('SourceInfo_ThumbnailPath_UNIQUE', table_name='SourceInfo')
    op.create_unique_constraint(op.f('SourceName_UNIQUE'), 'SourceInfo', ['SourceName'])
    op.create_unique_constraint(op.f('SourcePath_UNIQUE'), 'SourceInfo', ['SourcePath'])
    op.create_unique_constraint(op.f('ThumbnailPath_UNIQUE'), 'SourceInfo', ['ThumbnailPath'])
    op.drop_index('Study_StudyInstanceUid_UNIQUE', table_name='Study')
    op.create_unique_constraint(op.f('StudyInstanceUid_UNIQUE'), 'Study', ['StudyInstanceUid'])
    op.drop_index('Tag_TagName_UNIQUE', table_name='Tag')
    op.create_unique_constraint(op.f('TagName_UNIQUE'), 'Tag', ['TagName'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_Task_TaskState1_idx', table_name='Task')
    op.drop_index('fk_Task_TaskDefinition1_idx', table_name='Task')
    op.drop_constraint(op.f('TagName_UNIQUE'), 'Tag', type_='unique')
    op.create_index('Tag_TagName_UNIQUE', 'Tag', ['TagName'], unique=True)
    op.drop_index('fk_SubTaskImageLink_SubTask1_idx', table_name='SubTaskImageLink')
    op.drop_index('fk_SubTaskImageLink_ImageInstance1_idx', table_name='SubTaskImageLink')
    op.drop_index('fk_SubTask_TaskState1_idx', table_name='SubTask')
    op.drop_index('fk_SubTask_Task1_idx', table_name='SubTask')
    op.drop_index('fk_SubTask_Creator1_idx', table_name='SubTask')
    op.drop_index('fk_StudyTag_Tag1_idx', table_name='StudyTag')
    op.drop_index('fk_StudyTag_Study1_idx', table_name='StudyTag')
    op.drop_index('fk_Study_Patient1_idx', table_name='Study')
    op.drop_constraint(op.f('StudyInstanceUid_UNIQUE'), 'Study', type_='unique')
    op.create_index('Study_StudyInstanceUid_UNIQUE', 'Study', ['StudyInstanceUid'], unique=True)
    op.drop_constraint(op.f('ThumbnailPath_UNIQUE'), 'SourceInfo', type_='unique')
    op.drop_constraint(op.f('SourcePath_UNIQUE'), 'SourceInfo', type_='unique')
    op.drop_constraint(op.f('SourceName_UNIQUE'), 'SourceInfo', type_='unique')
    op.create_index('SourceInfo_ThumbnailPath_UNIQUE', 'SourceInfo', ['ThumbnailPath'], unique=True)
    op.create_index('SourceInfo_SourcePath_UNIQUE', 'SourceInfo', ['SourcePath'], unique=True)
    op.create_index('SourceInfo_SourceName_UNIQUE', 'SourceInfo', ['SourceName'], unique=True)
    op.drop_index('fk_Series_Study1_idx', table_name='Series')
    op.drop_constraint(op.f('SeriesInstanceUid_UNIQUE'), 'Series', type_='unique')
    op.create_index('Series_SeriesInstanceUid_UNIQUE', 'Series', ['SeriesInstanceUid'], unique=True)
    op.drop_constraint(op.f('ScanMode_UNIQUE'), 'Scan', type_='unique')
    op.create_index('Scan_ScanMode_UNIQUE', 'Scan', ['ScanMode'], unique=True)
    op.drop_constraint(op.f('ProjectName_UNIQUE'), 'Project', type_='unique')
    op.create_index('Project_ProjectName_UNIQUE', 'Project', ['ProjectName'], unique=True)
    op.drop_index('fk_Patient_Project1_idx', table_name='Patient')
    op.drop_constraint(op.f('ModalityTag_UNIQUE'), 'Modality', type_='unique')
    op.create_index('Modality_ModalityTag_UNIQUE', 'Modality', ['ModalityTag'], unique=True)
    op.drop_index('fk_ImageInstanceTag_Tag1_idx', table_name='ImageInstanceTag')
    op.drop_index('fk_ImageInstanceTag_ImageInstance1_idx', table_name='ImageInstanceTag')
    op.drop_index('fk_ImageInstance_SourceInfo1_idx', table_name='ImageInstance')
    op.drop_index('fk_ImageInstance_Series1_idx', table_name='ImageInstance')
    op.drop_index('fk_ImageInstance_Scan1_idx', table_name='ImageInstance')
    op.drop_index('fk_ImageInstance_Modality1_idx', table_name='ImageInstance')
    op.drop_index('fk_ImageInstance_Device1_idx', table_name='ImageInstance')
    op.drop_constraint(op.f('SOPInstanceUid_UNIQUE'), 'ImageInstance', type_='unique')
    op.create_index('ImageInstance_SOPInstanceUid_UNIQUE', 'ImageInstance', ['SOPInstanceUid'], unique=True)
    op.drop_constraint(op.f('SchemaName_UNIQUE'), 'FormSchema', type_='unique')
    op.create_index('FormSchema_SchemaName_UNIQUE', 'FormSchema', ['SchemaName'], unique=True)
    op.drop_constraint(op.f('FeatureName_UNIQUE'), 'Feature', type_='unique')
    op.create_index('Feature_FeatureName_UNIQUE', 'Feature', ['FeatureName'], unique=True)
    op.drop_constraint(op.f('CreatorName_UNIQUE'), 'Creator', type_='unique')
    op.create_index('Creator_CreatorName_UNIQUE', 'Creator', ['CreatorName'], unique=True)
    op.drop_index('fk_AnnotationTag_Tag1_idx', table_name='AnnotationTag')
    op.drop_index('fk_AnnotationTag_Annotation1_idx', table_name='AnnotationTag')
    op.drop_index('fk_AnnotationData_Annotation1_idx', table_name='AnnotationData')
    op.drop_constraint(op.f('DatasetIdentifier_UNIQUE'), 'AnnotationData', type_='unique')
    op.create_index('AnnotationData_DatasetIdentifier_UNIQUE', 'AnnotationData', ['DatasetIdentifier'], unique=True)
    op.drop_index('fk_Annotation_Study1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_Series1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_Patient1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_ImageInstance1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_Feature1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_Creator1_idx', table_name='Annotation')
    op.drop_index('fk_Annotation_AnnotationType1_idx', table_name='Annotation')
    # ### end Alembic commands ###
