"""test

Revision ID: c04645bec436
Revises: b9ef1a76ec71
Create Date: 2024-11-04 12:35:14.944393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04645bec436'
down_revision = 'b9ef1a76ec71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImageInstance', sa.Column('FDAIdentifier', sa.Integer(), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ImageInstance', 'FDAIdentifier')
    pass
    # ### end Alembic commands ###
