"""devices

Revision ID: c8c36b301f76
Revises: 781e14a57819
Create Date: 2025-03-21 12:33:00.843632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8c36b301f76'
down_revision = '781e14a57819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeviceModel',
    sa.Column('DeviceModelID', sa.Integer(), nullable=False),
    sa.Column('Manufacturer', sa.String(length=45), nullable=False),
    sa.Column('ManufacturerModelName', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('DeviceModelID', name=op.f('DeviceModelID')),
    sa.UniqueConstraint('Manufacturer', 'ManufacturerModelName', name='ManufacturerManufacturerModelName_UNIQUE')
    )
    op.create_table('DeviceInstance',
    sa.Column('DeviceInstanceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DeviceModelID', sa.Integer(), nullable=False),
    sa.Column('SerialNumber', sa.Text(), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['DeviceModelID'], ['DeviceModel.DeviceModelID'], name=op.f('fk_DeviceInstance_DeviceModel1')),
    sa.PrimaryKeyConstraint('DeviceInstanceID', name=op.f('DeviceInstanceID')),
    sa.UniqueConstraint('DeviceModelID', 'Description', name='DeviceModelIDDescription_UNIQUE')
    )
    op.add_column('ImageInstance', sa.Column('DeviceInstanceID', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_ImageInstance_DeviceInstance1'), 'ImageInstance', 'DeviceInstance', ['DeviceInstanceID'], ['DeviceInstanceID'])
    # Insert data from the old Device table into the new DeviceModel table
    op.execute("""
         INSERT INTO DeviceModel (DeviceModelID, Manufacturer, ManufacturerModelName)
         SELECT DeviceID, Manufacturer, ManufacturerModelName
         FROM Device
     """)
 
    # Insert data from the old Device table into the new DeviceInstance table
    op.execute("""
         INSERT INTO DeviceInstance (DeviceInstanceID, DeviceModelID, SerialNumber, Description)
         SELECT DeviceID, DeviceID, NULL, "DUMMY"
         FROM Device
     """)
    op.execute("""
         UPDATE ImageInstance
         SET DeviceInstanceID = DeviceID
     """)
    op.drop_index('ManufacturerManufacturerModelName_UNIQUE', table_name='Device')
    op.drop_constraint('fk_ImageInstance_Devices1', 'ImageInstance', type_='foreignkey')
    op.drop_index('fk_ImageInstance_Device1_idx', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_DeviceInstance1_idx', 'ImageInstance', ['DeviceInstanceID'], unique=False)
    op.drop_column('ImageInstance', 'DeviceID')
    op.drop_table('Device')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ImageInstance', sa.Column('DeviceID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_ImageInstance_DeviceInstance1'), 'ImageInstance', type_='foreignkey')
    op.create_foreign_key('fk_ImageInstance_Devices1', 'ImageInstance', 'Device', ['DeviceID'], ['DeviceID'])
    op.drop_index('fk_ImageInstance_DeviceInstance1_idx', table_name='ImageInstance')
    op.create_index('fk_ImageInstance_Device1_idx', 'ImageInstance', ['DeviceID'], unique=False)
    op.create_table('Device',
    sa.Column('DeviceID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Manufacturer', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('ManufacturerModelName', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('DeviceID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
     # Insert data back into the old Device table from the new DeviceModel table
    op.execute("""
         INSERT INTO Device (DeviceID, Manufacturer, ManufacturerModelName)
         SELECT DeviceModelID, Manufacturer, ManufacturerModelName
         FROM DeviceModel
     """)
    # Update the ImageInstance table to set the DeviceID column to the DeviceInstanceID values
    op.execute("""
         UPDATE ImageInstance
         JOIN DeviceInstance ON ImageInstance.DeviceInstanceID = DeviceInstance.DeviceInstanceID
         JOIN DeviceModel ON DeviceInstance.DeviceModelID = DeviceModel.DeviceModelID
         SET ImageInstance.DeviceID = DeviceModel.DeviceModelID
     """)
    op.drop_column('ImageInstance', 'DeviceInstanceID')
    op.create_index('ManufacturerManufacturerModelName_UNIQUE', 'Device', ['ManufacturerModelName', 'Manufacturer'], unique=True)
    op.drop_table('DeviceInstance')
    op.drop_table('DeviceModel')
    # ### end Alembic commands ###
