"""Prove, on every CI run, that the schema gates can still fail.

alembic check catches FK-action drift on all 83 foreign keys today -- but only
incidentally: it rests on the alembic==1.13.2 pin, on the MySQL dialect
reflecting FK `options`, and on env.py never gaining an include_object filter.
compare_server_default is newer still. Both are asserted here by mutating the
database and requiring the check to fail, so the day one stops working we hear
about it instead of enjoying a green check that measures nothing.

Every mutation restores in `finally`. A control that left the database altered
after a failed assertion would poison every step after it, and the failure
would be blamed on the wrong thing.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest
from alembic.command import check
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, text

from eyened_orm.config import load_database_settings
from eyened_orm.utils.env import env_flag_enabled

pytestmark = pytest.mark.mysql

MIGRATIONS_DIR = Path(__file__).resolve().parents[2] / "migrations"


@pytest.fixture(scope="module")
def engine():
    """A live MySQL migrated to head, or a skip.

    EYENED_REQUIRE_MYSQL_TESTS turns that skip into a failure. Without it a
    misconfigured job would skip both controls and still report green, which is
    the exact failure mode they exist to rule out.
    """
    try:
        settings = load_database_settings()
        engine = create_engine(
            f"mysql+pymysql://{settings.user}:{settings.password.get_secret_value()}"
            f"@{settings.host}:{settings.port}/{settings.database}"
        )
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except Exception as exc:
        if env_flag_enabled(os.environ.get("EYENED_REQUIRE_MYSQL_TESTS")):
            pytest.fail(f"EYENED_REQUIRE_MYSQL_TESTS is set but MySQL is unusable: {exc}")
        pytest.skip(f"no MySQL available: {exc}")
    return engine


@pytest.fixture(scope="module")
def alembic_config():
    config = Config(str(MIGRATIONS_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(MIGRATIONS_DIR / "alembic"))
    config.set_main_option("prepend_sys_path", "")
    return config


def _check_passes(config) -> bool:
    try:
        check(config)
        return True
    except AutogenerateDiffsDetected:
        return False


def test_stripping_on_update_makes_the_check_fail(engine, alembic_config):
    """compare_server_default's positive control."""
    assert _check_passes(alembic_config), "the check was already failing before this test"

    restore = (
        "ALTER TABLE Segmentation MODIFY DateModified datetime NULL "
        "DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
    )
    try:
        with engine.begin() as conn:
            conn.execute(text(
                "ALTER TABLE Segmentation MODIFY DateModified datetime NULL "
                "DEFAULT CURRENT_TIMESTAMP"
            ))
        assert not _check_passes(alembic_config), (
            "alembic check passed with ON UPDATE stripped from "
            "Segmentation.DateModified -- compare_server_default is not in force"
        )
    finally:
        with engine.begin() as conn:
            conn.execute(text(restore))

    assert _check_passes(alembic_config), "restoring the clause did not clear the diff"


def test_changing_a_foreign_key_action_makes_the_check_fail(engine, alembic_config):
    """Row 4 of the drift table on PR #222, pinned.

    CASCADE -> RESTRICT, not RESTRICT -> NO ACTION: alembic normalises that
    pair deliberately and InnoDB treats them identically, so it would prove
    nothing. The constraint is unnamed in the migration, so MySQL named it.
    """
    assert _check_passes(alembic_config), "the check was already failing before this test"

    with engine.connect() as conn:
        name = conn.execute(text(
            "SELECT rc.CONSTRAINT_NAME FROM information_schema.REFERENTIAL_CONSTRAINTS rc "
            "JOIN information_schema.KEY_COLUMN_USAGE kcu "
            "  ON kcu.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA "
            " AND kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME "
            "WHERE rc.CONSTRAINT_SCHEMA = DATABASE() "
            "  AND rc.TABLE_NAME = 'Segmentation' "
            "  AND kcu.COLUMN_NAME = 'ImageInstanceID' "
            "  AND rc.DELETE_RULE = 'CASCADE'"
        )).scalar()
    assert name, "Segmentation.ImageInstanceID has no ON DELETE CASCADE key to mutate"

    def readd(action: str) -> str:
        return (
            f"ALTER TABLE Segmentation ADD CONSTRAINT `{name}` "
            "FOREIGN KEY (ImageInstanceID) REFERENCES ImageInstance (ImageInstanceID) "
            f"ON DELETE {action}"
        )

    drop = f"ALTER TABLE Segmentation DROP FOREIGN KEY `{name}`"
    try:
        with engine.begin() as conn:
            conn.execute(text(drop))
            conn.execute(text(readd("RESTRICT")))
        assert not _check_passes(alembic_config), (
            f"alembic check passed with {name} changed from CASCADE to RESTRICT -- "
            "FK action drift is no longer detected"
        )
    finally:
        with engine.begin() as conn:
            conn.execute(text(drop))
            conn.execute(text(readd("CASCADE")))

    assert _check_passes(alembic_config), "restoring the action did not clear the diff"
